<?php $this->GetMesseger(); ?>
[<a href="/admin/category/new">New Category</a>]
<table>
    <tr>
        <td>
            Name
        </td>
        <td>
            Status
        </td>
        <td>
            Description
        </td>
        <td>
            Options
        </td>
    </tr>
<?php foreach($this->listingCategory as $index): ?>
    <tr>
        <td>
            <?php echo $index['category_name']; ?>
        </td>
        <td>
            <?php if($index['category_public'] == 1){ ?>
            public
            <?php } else { ?>
            no public
            <?php } ?>
        </td>
        <td>
            <?php echo $index['category_description']; ?>
        </td>
        <td>
            [<a href="/admin/category/edit/id/<?php echo $index['category_id']; ?>">Edit</a>]
            <?php if($index['category_public'] == 1){ ?>
            [<a href="/admin/category/unpublish/id/<?php echo $index['category_id']; ?>">unpublis</a>]
            <?php } else { ?>
            [<a href="/admin/category/publish/id/<?php echo $index['category_id']; ?>">publish</a>]
            <?php } ?>
        </td>
    </tr>
<?php endforeach; ?>
</table>