
<div class="wLight" >
   <div  id="processed" class="popup">
          <div class="" >
                <div class="closex">X</div>
                <h1>
                        BEFORE YOU GO...
                </h1> 
                <br/>
                <input type="text" value="" placeholder="name@email.com"  />
                <br/>
                <p class="small">
                    Sign up for daily reminds and be entered to win a 24kt. gold mystery gift offered exclusively to our registered users every month. <br/>
                    And unlike the other guys, we’ll never share your email address. You’re privacy is our priority. Guaranteed. Get adorned!
                </p>
                <a href="" class="btn btn-negro">Continue</a>
          </div>

       

    </div>

</div>