
<div class="wLight" >
   <div  id="processed" class="popup">
          <div class="" >
                <div class="closex"></div>
                <h1>
                        WELCOME
                </h1>
                <br/>
                <p class="small">
                     Welcome to the limited edition,<br/> pre-launch wetheadorned special. <br/>To continue shopping, simply enter your email <br/>below and let the fun begin. Get adorned!
                </p><br/>
                <form id="susbcriptions" name="susbcriptions" >
                    <input type="text" value="" placeholder="name@email.com" name="input_suscription" id="input_suscription"/>
                </form>
                <a href="" class="btn btn-negro" id="saveSubscription">Continue</a>
          </div>

    </div>
</div>
<script>
    WTA.initFormSubscriptions();
</script>