<div class="box span12">
    <div class="box-header well" data-original-title>
        <h2>Orders List</h2>
    </div>
    <div class="box-content">
        <form method="get" action="">
            <div class="span4">
                <h3>Filters <a href="#" id="plusFilter"  class="icon-plus"></a></h3>
                <div class="well" id="filter" style="display:none">

                    <h4>Date Range</h4>
                    <div class="control-group" style="text-align: left">
                        <label class="control-label" for="fromDate">From Date</label>
                        <div class="controls">
                            <input type="text" class="datepicker" value="<?php echo $this->fromDate; ?>" id="fromDate" name="fromDate" value="">
                        </div>
                    </div>
                    <div class="control-group" style="text-align: left">
                        <label class="control-label" for="toDate">To Date</label>
                        <div class="controls">
                            <input type="text" class="datepicker" value="<?php echo $this->toDate; ?>" id="toDate" name="toDate" value="">
                        </div>
                    </div>

                    <h4>Member</h4>
                    <div class="control-group">
                        <label class="control-label" for="menbers">Select Member</label>
                        <div class="controls">
                            <select style="width: 210px;" id="menbers" name="menbers[]" multiple data-rel="chosen">
                                <?php foreach ($this->userOrders as $index): ?>
                                    <option value="<?php echo $index['member_id'] ?>" <?php echo in_array($index['member_id'], $this->menbers) ? 'selected' : '' ?> ><?php echo $index['member_name'] . ' ' . $index['member_last_name'] ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    
                    <h4>Country</h4>
                    <div class="control-group">
                        <label class="control-label" for="countries">Select Countries</label>
                        <div class="controls">
                            <select style="width: 210px;" id="countries" name="countries" data-rel="chosen">
                                <option value="" ></option>
                                <?php foreach ($this->country as $index): ?>
                                    <option value="<?php echo $index['id'] ?>" <?php echo ($index['id'] == $this->countrySelect) ? 'selected' : '' ?> ><?php echo $index['country'] ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <h4>State</h4>
                    <div class="control-group">
                        <label class="control-label" for="state">Select State</label>
                        <div class="controls">
                            <select id="state" name="state" >
                                <?php foreach ($this->subRegions as $index): ?>
                                    <option value="<?php echo $index['id'] ?>" <?php echo ($index['id'] == $this->subRegionsSelect) ? 'selected' : '' ?> ><?php echo $index['name'] ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <h4>Status</h4>
                    <div class="control-group" style="text-align: left">
                        <?php
                        $state = array(
                            Application_Entity_Transaction::TRANSACTION_OUTSTANDING => 'OUTSTANDING',
                            Application_Entity_Transaction::TRANSACTION_PAID => 'PAID',
                            Application_Entity_Transaction::TRANSACTION_REMOVED => 'REMOVED'
                        );
                        ?>
                        <?php foreach ($state as $index => $value): ?>
                            <label>
                                <input <?php echo in_array($index, $this->status) ? 'checked="checked"' : '' ?> type="checkbox" id="status<?php echo $index; ?>" name="status[]" value="<?php echo $index; ?>" /><?php echo $value; ?>
                            </label>
                        <?php endforeach; ?>

                    </div>

                    <h4>Delivered</h4>
                    <div class="control-group" style="text-align: left">
                        <?php
                        $stateDelivered = array(
                            1 => 'Yes',
                            0 => 'No'
                        );
                        ?>
                        <?php foreach ($stateDelivered as $index => $value): ?>
                            <label><input <?php echo in_array($index, $this->stateDelivered) ? 'checked="checked"' : '' ?> type="checkbox" id="stateDelivered<?php echo $index; ?>" name="stateDelivered[]" value="<?php echo $index; ?>" /><?php echo $value; ?></label>
                        <?php endforeach; ?>

                    </div>
                    <div style="text-align: right">
                        <a href="/admin/orders">Cancel Filter</a>
                        <input type="submit" value="Send" />
                    </div>
                </div>
            </div>

        </form> 
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Registration Date
                    </th>
                    <th>
                        Member
                    </th>
                    <th>
                        Status
                    </th>
                    <th>
                        Product
                    </th>
                    <th>
                        Delivered
                    </th>
                    <th>
                        Delivered Date
                    </th>
                </tr>
            </thead>
            <?php foreach ($this->orders as $index): $priceTotal=0; ?>
                <tr>
                    <td>
                        <?php echo $index['transaction_payment_date']; ?>
                    </td>
                    <td>
                        
                            <?php echo $index['member_name']; ?> 
                            <?php echo $index['member_last_name']; ?>
                    </td>
                    <td>
                        <?php echo $index['tansaction_state_name']; ?>
                    </td>
                    <td>
                        <?php $arrayProducts = explode('[]', $index['product']);
                        ?>
                        <table class="table table-bordered table-striped table-condensed">
                            <thead>
                                <tr>
                                    <th>
                                        Code
                                    </th>
                                    <th>
                                        Product
                                    </th>
                                    <th>
                                        Quantity
                                    </th>
                                    <th>
                                        G. Price
                                    </th>
                                    <th>
                                        M. Price
                                    </th>
                                    <th>
                                        Size
                                    </th>

                                </tr>
                            </thead>
                            <?php
                            foreach ($arrayProducts as $index2) {
                                $product = explode('|', $index2);
                                ?>
                                <tr>
                                    <td>
                                        <?php echo $product[5]; ?>
                                    </td>

                                    <td>
                                        <?php echo $product[0]; ?>
                                    </td>
                                    <td>
                                        <?php echo $product[1]; ?>
                                    </td>
                                    <?php
                                    if ($index['transaction_user_menbership'] == 1) {
                                        $price = $product[3];
                                        ?>
                                        <td style="text-decoration: line-through">
                                            $<?php echo $product[2]; ?>
                                        </td>
                                        <td>
                                            <span class="label label-success">$<?php echo $product[3]; ?></span>
                                        </td>
                                    <?php } else {
                                        $price = $product[2]; ?>
                                        <td>
                                            <span class="label label-success">$<?php echo $product[2]; ?></span>
                                        </td>
                                        <td style="text-decoration: line-through" >
                                            $<?php echo $product[3]; ?>
                                        </td>
                                    <?php } ?>
                                    <td >
                                        <?php echo $product[4]; ?>
                                    </td>

                                </tr>

                                <?php
                                $priceTotal += $product[1] * $price;
                            }
                            ?>
                            <tr>
                                <td colspan="3" >

                                </td >
                                <td  style="background-color: #DD5600; color: #ffffff; text-align: right" >
                                    Total: &nbsp;   
                                </td>
                                <td colspan="2" style="background-color: #DD5600; color: #ffffff;  text-align: right">
                                    $<?php echo $priceTotal; ?>
                                </td>
                            </tr>
                        </table>
                    </td>
                    <td>
                        <?php
                        $arrayEstatus = array('No', 'Yes');
                        echo $arrayEstatus[$index['transaction_delivered']];
                        ?> 
                    </td>
                    <td>
                        <?php
                        echo $index['transaction_delivered_date'];
                        ?> 
                    </td>
                    <td>
                        <?php if ($index['tansaction_state_id'] == 2) { ?>
                            <?php if ($index['transaction_delivered'] == 1) { ?>
                                <a href="/admin/orders/undelivered?id=<?php echo $index['transaction_id']; ?>" class="btn btn-mini btn-info"> <span class="icon-arrow-down icon-white"></span>Undelivered</a>

                            <?php } else { ?>
                                <a href="/admin/orders/delivered?id=<?php echo $index['transaction_id']; ?>" class="btn btn-mini btn-info"> <span class="icon-arrow-up icon-white"></span>Delivered</a>
                            <?php } ?>
                        <?php } ?>
                    </td>
                    <td>                        <a href="#" id="<?php echo $index['transaction_id']; ?>" title="<?php echo $index['member_name']; ?> <?php echo $index['member_last_name']; ?>" class="btn-setting">View More
                        </a>
</td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>

<div class="modal hide fade" id="myModal">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3 id="contact"></h3>
    </div>
    <div class="modal-body">
        <dl>
            <dt>Contact information </dt>
            <dd id="mail"></dd>
            <dd id="phone"></dd>
            <dd id="fax"></dd>

            <dt>Billing address</dt>
            <dd id="billFirstName"></dd>
            <dd id="billLastName"></dd>
            <dd id="billAddres"></dd>
            <dd id="billAddresContinued"></dd>
            <dd id="billRegion"></dd>
            <dd id="billSubRegion"></dd>
            <dd id="billCity"></dd>
            <dd id="billPostalCode"></dd>
            <dd id="billPhone"></dd>

            <dt>Shipping address</dt>
            <dd id="shiFirstName"></dd>
            <dd id="shiLastName"></dd>
            <dd id="shiAddres"></dd>
            <dd id="shiAddresContinued"></dd>
            <dd id="shiRegion"></dd>
            <dd id="shiSubRegion"></dd>
            <dd id="shiCity"></dd>
            <dd id="shiPostalCode"></dd>
            <dd id="shiPhone"></dd>

            <dt>Payment Method</dt>
            <dd id="cardNumber"></dd>
            <dd id="cardType"></dd>
            <dd id="expire"></dd>
        </dl>            
    </div>
    <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal">Close</a>

    </div>
</div>





