<div class="box span12">
    <div class="box-header well" data-original-title>
        <h2>Product List</h2>
    </div>
    <div class="box-content">
        <form>
            <div class="span4">
                <h3>Filters</h3>
                <div class="well">
                    
                    <h4>Date Range</h4>
                    <div class="control-group" style="text-align: left">
                        <label class="control-label" for="date01">From Date</label>
                        <div class="controls">
                            <input type="text" class="datepicker" id="date01" value="">
                        </div>
                    </div>
                    <div class="control-group" style="text-align: left">
                        <label class="control-label" for="date02">To Date</label>
                        <div class="controls">
                            <input type="text" class="datepicker" id="date02" value="">
                        </div>
                    </div>
                    <h4>State</h4>
                    <div class="control-group" style="text-align: left">
                        <?php
                        $state = array(
                            Application_Entity_Transaction::TRANSACTION_OUTSTANDING => 'OUTSTANDING',
                            Application_Entity_Transaction::TRANSACTION_PAID => 'PAID',
                            Application_Entity_Transaction::TRANSACTION_REMOVED => 'REMOVED'
                        );
                        ?>
                        <?php foreach ($state as $index => $value): ?>
                            <label><input type="checkbox" id="state<?php echo $index; ?>" name="state[]" value="<?php echo $index; ?>" /><?php echo $value; ?></label>
                        <?php endforeach; ?>

                    </div>

                    <h4>Devoted</h4>
                    <div class="control-group" style="text-align: left">
                        <?php
                        $stateDevoted = array(
                            1 => 'Yes',
                            0 => 'No'
                        );
                        ?>
                        <?php foreach ($stateDevoted as $index => $value): ?>
                            <label><input type="checkbox" id="stateDevoted<?php echo $index; ?>" name="stateDevoted[]" value="<?php echo $index; ?>" /><?php echo $value; ?></label>
                        <?php endforeach; ?>

                    </div>
                    <div style="text-align: right">
                    <input type="submit" value="Send" />
                    </div>
                </div>
            </div>
            
        </form> 
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Fecha de pago
                    </th>
                    <th>
                        Cliente
                    </th>
                    <th>
                        Estado
                    </th>
                    <th>
                        Productos
                    </th>
                    <th>
                        Entregado
                    </th>
                </tr>
            </thead>
            <?php foreach ($this->orders as $index): ?>
                <tr>
                    <td>
                        <?php echo $index['transaction_payment_date']; ?>
                    </td>
                    <td>
                        <?php echo $index['member_name']; ?> 
                        <?php echo $index['member_last_name']; ?>
                    </td>
                    <td>
                        <?php echo $index['tansaction_state_name']; ?>
                    </td>
                    <td>
                        <?php $arrayProducts = explode('[]', $index['product']);
                        ?>
                        <table class="table table-bordered table-striped table-condensed">
                            <thead>
                                <tr>
                                    <th>
                                        Name Product
                                    </th>
                                    <th>
                                        Quantity
                                    </th>
                                    <th>
                                        Amount
                                    </th>
                                </tr>
                            </thead>
                            <?php
                            foreach ($arrayProducts as $index2) {
                                $product = explode('|', $index2);
                                ?>
                                <tr>
                                    <td>
                                        <?php echo $product[0]; ?>
                                    </td>
                                    <td>
                                        <?php echo $product[1]; ?>
                                    </td>
                                    <td>
                                        <?php echo $product[2]; ?>
                                    </td>
                                    <td>
                                        <?php echo $product[3]; ?>
                                    </td>

                                </tr>    
                                <?php
                            }
                            ?>
                        </table>
                    </td>
                    <td>
                        <?php
                        $arrayEstatus = array('not', 'yes');
                        echo $arrayEstatus[$index['transaction_devoted']];
                        ?> 
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>


