<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-type" content="text/html;charset=UTF-8">
        <?php $this->headTitle() ?>
        <?php $this->headMeta() ?>
        <!-- The styles -->
        <link id="bs-css" href="<?php echo STATIC_URL . '/admin/'; ?>css/bootstrap-cerulean.css" rel="stylesheet">
        <style type="text/css">
            body {
                padding-bottom: 40px;
            }
            .sidebar-nav {
                padding: 9px 0;
            }
        </style>
        <link href="<?php echo STATIC_URL . '/admin/'; ?>css/bootstrap-responsive.css" rel="stylesheet">
        <link href="<?php echo STATIC_URL . '/admin/'; ?>css/charisma-app.css" rel="stylesheet">
        <link href="<?php echo STATIC_URL . '/admin/'; ?>css/jquery-ui-1.8.21.custom.css" rel="stylesheet">
        <link href='<?php echo STATIC_URL . '/admin/'; ?>css/fullcalendar.css' rel='stylesheet'>
        <link href='<?php echo STATIC_URL . '/admin/'; ?>css/fullcalendar.print.css' rel='stylesheet'  media='print'>
        <link href='<?php echo STATIC_URL . '/admin/'; ?>css/chosen.css' rel='stylesheet'>
        <link href='<?php echo STATIC_URL . '/admin/'; ?>css/uniform.default.css' rel='stylesheet'>
        <link href='<?php echo STATIC_URL . '/admin/'; ?>css/colorbox.css' rel='stylesheet'>
        <link href='<?php echo STATIC_URL . '/admin/'; ?>css/jquery.cleditor.css' rel='stylesheet'>
        <link href='<?php echo STATIC_URL . '/admin/'; ?>css/jquery.noty.css' rel='stylesheet'>
        <link href='<?php echo STATIC_URL . '/admin/'; ?>css/noty_theme_default.css' rel='stylesheet'>
        <link href='<?php echo STATIC_URL . '/admin/'; ?>css/elfinder.min.css' rel='stylesheet'>
        <link href='<?php echo STATIC_URL . '/admin/'; ?>css/elfinder.theme.css' rel='stylesheet'>
        <link href='<?php echo STATIC_URL . '/admin/'; ?>css/jquery.iphone.toggle.css' rel='stylesheet'>
        <link href='<?php echo STATIC_URL . '/admin/'; ?>css/opa-icons.css' rel='stylesheet'>
        <link href='<?php echo STATIC_URL . '/admin/'; ?>css/uploadify.css' rel='stylesheet'>

        <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <!-- The fav icon -->
        <link rel="shortcut icon" href="img/favicon.ico">
        <?php $this->headLink() ?>

        
        <?php $this->headStyle() ?>       
    </head>
    <body>
        <!-- topbar starts -->
        <div class="navbar">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".top-nav.nav-collapse,.sidebar-nav.nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
<!--                    <a class="brand" href="index.html"> <img alt="Charisma Logo" src="img/logo20.png" /> <span>Admin Wta</span></a>-->


                    <!-- theme selector ends -->

                    <!-- user dropdown starts -->
                    <div class="btn-group pull-right" >
                        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="icon-user"></i><span class="hidden-phone"> admin</span>
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Profile</a></li>
                            <li class="divider"></li>
                            <li><a href="/admin/logout">Logout</a></li>
                        </ul>
                    </div>
                    <!-- user dropdown ends -->

                    <div class="top-nav nav-collapse">
                        
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <!-- topbar ends -->
        <div class="container-fluid">
            <div class="row-fluid">

                <!-- left menu starts -->
                <div class="span2 main-menu-span">
                    <div class="well nav-collapse sidebar-nav">
                        <?php echo $this->navigation()->menu()->render(); ?>
<!--                        <ul class="nav nav-tabs nav-stacked main-menu">
                            <li class="nav-header hidden-tablet">Main</li>
                            <li><a class="ajax-link" href="index.html"><i class="icon-home"></i><span class="hidden-tablet"> Dashboard</span></a></li>
                            <li><a class="ajax-link" href="ui.html"><i class="icon-eye-open"></i><span class="hidden-tablet"> UI Features</span></a></li>
                            <li><a class="ajax-link" href="form.html"><i class="icon-edit"></i><span class="hidden-tablet"> Forms</span></a></li>
                            <li><a class="ajax-link" href="chart.html"><i class="icon-list-alt"></i><span class="hidden-tablet"> Charts</span></a></li>
                            <li><a class="ajax-link" href="typography.html"><i class="icon-font"></i><span class="hidden-tablet"> Typography</span></a></li>
                            <li><a class="ajax-link" href="gallery.html"><i class="icon-picture"></i><span class="hidden-tablet"> Gallery</span></a></li>
                            <li class="nav-header hidden-tablet">Sample Section</li>
                            <li><a class="ajax-link" href="table.html"><i class="icon-align-justify"></i><span class="hidden-tablet"> Tables</span></a></li>
                            <li><a class="ajax-link" href="calendar.html"><i class="icon-calendar"></i><span class="hidden-tablet"> Calendar</span></a></li>
                            <li><a class="ajax-link" href="grid.html"><i class="icon-th"></i><span class="hidden-tablet"> Grid</span></a></li>
                            <li><a class="ajax-link" href="file-manager.html"><i class="icon-folder-open"></i><span class="hidden-tablet"> File Manager</span></a></li>
                            <li><a href="tour.html"><i class="icon-globe"></i><span class="hidden-tablet"> Tour</span></a></li>
                            <li><a class="ajax-link" href="icon.html"><i class="icon-star"></i><span class="hidden-tablet"> Icons</span></a></li>
                            <li><a href="error.html"><i class="icon-ban-circle"></i><span class="hidden-tablet"> Error Page</span></a></li>
                            <li><a href="login.html"><i class="icon-lock"></i><span class="hidden-tablet"> Login Page</span></a></li>
                        </ul>-->
                        
                    </div><!--/.well -->
                </div><!--/span-->
                <!-- left menu ends -->

                <noscript>
                    <div class="alert alert-block span10">
                        <h4 class="alert-heading">Warning!</h4>
                        <p>You need to have <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> enabled to use this site.</p>
                    </div>
                </noscript>

                <div id="content" class="span10">
                    <div>
                        <?php echo $this->navigation()->breadcrumbs()->render(); ?>
<!--				<ul class="breadcrumb">
					<li>
						<a href="#">Home</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="#">Forms</a>
					</li>
				</ul>-->
			</div>
                    <div class="row-fluid sortable">
                    <?php echo $this->getMessegerAdmin(); ?>
                    <?php echo $this->layout()->content ?>
                        </div>
                </div><!--/#content.span10-->
            </div><!--/fluid-row-->

            <hr>

            <div class="modal hide fade" id="myModal">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">×</button>
                    <h3>Settings</h3>
                </div>
                <div class="modal-body">
                    <p>Here settings can be configured...</p>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn" data-dismiss="modal">Close</a>
                    <a href="#" class="btn btn-primary">Save changes</a>
                </div>
            </div>

            <footer>
                <p class="pull-left">&copy; <a href="<?php echo BASE_URL; ?>" target="_blank"><?php echo NAME_SITE; ?></a> <?php echo date('Y') ?></p>
<!--                <p class="pull-right">Powered by: <a href="http://www.intagono.com">Intagono</a></p>-->
            </footer>

        </div><!--/.fluid-container-->
        <!-- external javascript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->

        <!-- jQuery -->
        <script src="<?php echo $this->versioning('/admin/js/jquery-1.7.2.min.js'); ?>"></script>
        <!-- jQuery UI -->
        <script src="<?php echo $this->versioning('/admin/js/jquery-ui-1.8.21.custom.min.js'); ?>"></script>
        <!-- transition / effect library -->
        <script src="<?php echo $this->versioning('/admin/js/bootstrap-transition.js'); ?>"></script>
        <!-- alert enhancer library -->
        <script src="<?php echo $this->versioning('/admin/js/bootstrap-alert.js'); ?>"></script>
        <!-- modal / dialog library -->
        <script src="<?php echo $this->versioning('/admin/js/bootstrap-modal.js'); ?>"></script>
        <!-- custom dropdown library -->
        <script src="<?php echo $this->versioning('/admin/js/bootstrap-dropdown.js'); ?>"></script>
        <!-- scrolspy library -->
        <script src="<?php echo $this->versioning('/admin/js/bootstrap-scrollspy.js'); ?>"></script>
        <!-- library for creating tabs -->
        <script src="<?php echo $this->versioning('/admin/js/bootstrap-tab.js'); ?>"></script>
        <!-- library for advanced tooltip -->
        <script src="<?php echo $this->versioning('/admin/js/bootstrap-tooltip.js'); ?>"></script>
        <!-- popover effect library -->
        <script src="<?php echo $this->versioning('/admin/js/bootstrap-popover.js'); ?>"></script>
        <!-- button enhancer library -->
        <script src="<?php echo $this->versioning('/admin/js/bootstrap-button.js'); ?>"></script>
        <!-- accordion library (optional, not used in demo) -->
        <script src="<?php echo $this->versioning('/admin/js/bootstrap-collapse.js'); ?>"></script>
        <!-- carousel slideshow library (optional, not used in demo) -->
        <script src="<?php echo $this->versioning('/admin/js/bootstrap-carousel.js'); ?>"></script>
        <!-- autocomplete library -->
        <script src="<?php echo $this->versioning('/admin/js/bootstrap-typeahead.js'); ?>"></script>
        <!-- tour library -->
        <script src="<?php echo $this->versioning('/admin/js/bootstrap-tour.js'); ?>"></script>
        <!-- library for cookie management -->
        <script src="<?php echo $this->versioning('/admin/js/jquery.cookie.js'); ?>"></script>
        <!-- calander plugin -->
        <script src=""<?php echo $this->versioning('/admin/js/fullcalendar.min.js'); ?>"></script>
        <!-- data table plugin -->
        <script src="<?php echo $this->versioning('/admin/js/jquery.dataTables.min.js'); ?>"></script>

        <!-- chart libraries start -->
        <script src="<?php echo $this->versioning('/admin/js/excanvas.js'); ?>"></script>
        <script src="<?php echo $this->versioning('/admin/js/jquery.flot.min.js'); ?>"></script>
        <script src="<?php echo $this->versioning('/admin/js/jquery.flot.pie.min.js'); ?>"></script>
        <script src="<?php echo $this->versioning('/admin/js/jquery.flot.stack.js'); ?>"></script>
        <script src="<?php echo $this->versioning('/admin/js/jquery.flot.resize.min.js'); ?>"></script>
        <!-- chart libraries end -->

        <!-- select or dropdown enhancer -->
        <script src="<?php echo $this->versioning('/admin/js/jquery.chosen.min.js'); ?>"></script>
        <!-- checkbox, radio, and file input styler -->
        <script src="<?php echo $this->versioning('/admin/js/jquery.uniform.min.js'); ?>"></script>
        <!-- plugin for gallery image view -->
        <script src="<?php echo $this->versioning('/admin/js/jquery.colorbox.min.js'); ?>"></script>
        <!-- rich text editor library -->
        <script src="<?php echo $this->versioning('/admin/js/jquery.cleditor.min.js'); ?>"></script>
        <!-- notification plugin -->
        <script src="<?php echo $this->versioning('/admin/js/jquery.noty.js'); ?>"></script>
        <!-- file manager library -->
        <script src="<?php echo $this->versioning('/admin/js/jquery.elfinder.min.js'); ?>"></script>
        <!-- star rating plugin -->
        <script src="<?php echo $this->versioning('/admin/js/jquery.raty.min.js'); ?>"></script>
        <!-- for iOS style toggle switch -->
        <script src="<?php echo $this->versioning('/admin/js/jquery.iphone.toggle.js'); ?>"></script>
        <!-- autogrowing textarea plugin -->
        <script src="<?php echo $this->versioning('/admin/js/jquery.autogrow-textarea.js'); ?>"></script>
        <!-- multiple file upload plugin -->
        <script src="<?php echo $this->versioning('/admin/js/jquery.uploadify-3.1.min.js'); ?>"></script>
        <!-- history.js for cross-browser state change on ajax -->
        <script src="<?php echo $this->versioning('/admin/js/jquery.history.js'); ?>"></script>
        <!-- application script for Charisma demo -->
        <script>
            var url_satic='<?php echo STATIC_URL . '/admin/'; ?>';
        </script>
        <script src="<?php echo $this->versioning('/admin/js/charisma.js'); ?>"></script>
        <?php echo $this->headScript() ?>
    </body>
</html>