<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-type" content="text/html;charset=UTF-8">
        <?php $this->headTitle() ?>
        <?php $this->headMeta() ?>
        <?php $this->headLink() ?>

        <?php $this->headScript() ?>
        <?php $this->headStyle() ?>       
    </head>
    <body>
                <?php echo $this->getMessegerAdmin(); ?>
                <?php echo $this->navigation()->menu()->render(); ?>
                <?php echo $this->navigation()
                        ->breadcrumbs()
                        ->setMinDepth(0)
                        ->setLinkLast(true)
                        ->setSeparator(" &raquo; " . PHP_EOL); 
                ?>
                <?php echo $this->layout()->content ?>

    </body>
</html>