<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-type" content="text/html;charset=UTF-8">
        <?php $this->headTitle() ?>
        <?php $this->headMeta() ?>
        <!-- The styles -->
        <link id="bs-css" href="<?php echo STATIC_URL . '/admin/'; ?>css/bootstrap-cerulean.css" rel="stylesheet">
        <style type="text/css">
            body {
                padding-bottom: 40px;
            }
            .sidebar-nav {
                padding: 9px 0;
            }
        </style>
        <link href="<?php echo STATIC_URL . '/admin/'; ?>css/bootstrap-responsive.css" rel="stylesheet">
        <link href="<?php echo STATIC_URL . '/admin/'; ?>css/charisma-app.css" rel="stylesheet">
        <link href="<?php echo STATIC_URL . '/admin/'; ?>css/jquery-ui-1.8.21.custom.css" rel="stylesheet">
        <link href='<?php echo STATIC_URL . '/admin/'; ?>css/fullcalendar.css' rel='stylesheet'>
        <link href='<?php echo STATIC_URL . '/admin/'; ?>css/fullcalendar.print.css' rel='stylesheet'  media='print'>
        <link href='<?php echo STATIC_URL . '/admin/'; ?>css/chosen.css' rel='stylesheet'>
        <link href='<?php echo STATIC_URL . '/admin/'; ?>css/uniform.default.css' rel='stylesheet'>
        <link href='<?php echo STATIC_URL . '/admin/'; ?>css/colorbox.css' rel='stylesheet'>
        <link href='<?php echo STATIC_URL . '/admin/'; ?>css/jquery.cleditor.css' rel='stylesheet'>
        <link href='<?php echo STATIC_URL . '/admin/'; ?>css/jquery.noty.css' rel='stylesheet'>
        <link href='<?php echo STATIC_URL . '/admin/'; ?>css/noty_theme_default.css' rel='stylesheet'>
        <link href='<?php echo STATIC_URL . '/admin/'; ?>css/elfinder.min.css' rel='stylesheet'>
        <link href='<?php echo STATIC_URL . '/admin/'; ?>css/elfinder.theme.css' rel='stylesheet'>
        <link href='<?php echo STATIC_URL . '/admin/'; ?>css/jquery.iphone.toggle.css' rel='stylesheet'>
        <link href='<?php echo STATIC_URL . '/admin/'; ?>css/opa-icons.css' rel='stylesheet'>
        <link href='<?php echo STATIC_URL . '/admin/'; ?>css/uploadify.css' rel='stylesheet'>

        <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <!-- The fav icon -->
        <link rel="shortcut icon" href="img/favicon.ico">
        <?php $this->headLink() ?>

        <?php $this->headScript() ?>
        <?php $this->headStyle() ?>       
    </head>
    <body>
        
        
        <div class="container-fluid">
		<div class="row-fluid">
		
			<div class="row-fluid">
				<div class="span12 center login-header">
					<h2>Welcome to WTA Admin</h2>
				</div><!--/span-->
			</div><!--/row-->
			
			<div class="row-fluid">
				<div class="well span5 center login-box">
                                    <?php echo $this->layout()->content ?>
				</div><!--/span-->
			</div><!--/row-->
				</div><!--/fluid-row-->
		
	</div><!--/.fluid-container-->
        
        <!-- external javascript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->

        <!-- jQuery -->
        <script src="<?php echo $this->versioning('/admin/js/jquery-1.7.2.min.js'); ?>"></script>
        <!-- jQuery UI -->
        <script src="<?php echo $this->versioning('/admin/js/jquery-ui-1.8.21.custom.min.js'); ?>"></script>
        <!-- transition / effect library -->
        <script src="<?php echo $this->versioning('/admin/js/bootstrap-transition.js'); ?>"></script>
        <!-- alert enhancer library -->
        <script src="<?php echo $this->versioning('/admin/js/bootstrap-alert.js'); ?>"></script>
        <!-- modal / dialog library -->
        <script src="<?php echo $this->versioning('/admin/js/bootstrap-modal.js'); ?>"></script>
        <!-- custom dropdown library -->
        <script src="<?php echo $this->versioning('/admin/js/bootstrap-dropdown.js'); ?>"></script>
        <!-- scrolspy library -->
        <script src="<?php echo $this->versioning('/admin/js/bootstrap-scrollspy.js'); ?>"></script>
        <!-- library for creating tabs -->
        <script src="<?php echo $this->versioning('/admin/js/bootstrap-tab.js'); ?>"></script>
        <!-- library for advanced tooltip -->
        <script src="<?php echo $this->versioning('/admin/js/bootstrap-tooltip.js'); ?>"></script>
        <!-- popover effect library -->
        <script src="<?php echo $this->versioning('/admin/js/bootstrap-popover.js'); ?>"></script>
        <!-- button enhancer library -->
        <script src="<?php echo $this->versioning('/admin/js/bootstrap-button.js'); ?>"></script>
        <!-- accordion library (optional, not used in demo) -->
        <script src="<?php echo $this->versioning('/admin/js/bootstrap-collapse.js'); ?>"></script>
        <!-- carousel slideshow library (optional, not used in demo) -->
        <script src="<?php echo $this->versioning('/admin/js/bootstrap-carousel.js'); ?>"></script>
        <!-- autocomplete library -->
        <script src="<?php echo $this->versioning('/admin/js/bootstrap-typeahead.js'); ?>"></script>
        <!-- tour library -->
        <script src="<?php echo $this->versioning('/admin/js/bootstrap-tour.js'); ?>"></script>
        <!-- library for cookie management -->
        <script src="<?php echo $this->versioning('/admin/js/jquery.cookie.js'); ?>"></script>
        <!-- calander plugin -->
        <script src=""<?php echo $this->versioning('/admin/js/fullcalendar.min.js'); ?>"></script>
        <!-- data table plugin -->
        <script src="<?php echo $this->versioning('/admin/js/jquery.dataTables.min.js'); ?>"></script>

        <!-- chart libraries start -->
        <script src="<?php echo $this->versioning('/admin/js/excanvas.js'); ?>"></script>
        <script src="<?php echo $this->versioning('/admin/js/jquery.flot.min.js'); ?>"></script>
        <script src="<?php echo $this->versioning('/admin/js/jquery.flot.pie.min.js'); ?>"></script>
        <script src="<?php echo $this->versioning('/admin/js/jquery.flot.stack.js'); ?>"></script>
        <script src="<?php echo $this->versioning('/admin/js/jquery.flot.resize.min.js'); ?>"></script>
        <!-- chart libraries end -->

        <!-- select or dropdown enhancer -->
        <script src="<?php echo $this->versioning('/admin/js/jquery.chosen.min.js'); ?>"></script>
        <!-- checkbox, radio, and file input styler -->
        <script src="<?php echo $this->versioning('/admin/js/jquery.uniform.min.js'); ?>"></script>
        <!-- plugin for gallery image view -->
        <script src="<?php echo $this->versioning('/admin/js/jquery.colorbox.min.js'); ?>"></script>
        <!-- rich text editor library -->
        <script src="<?php echo $this->versioning('/admin/js/jquery.cleditor.min.js'); ?>"></script>
        <!-- notification plugin -->
        <script src="<?php echo $this->versioning('/admin/js/jquery.noty.js'); ?>"></script>
        <!-- file manager library -->
        <script src="<?php echo $this->versioning('/admin/js/jquery.elfinder.min.js'); ?>"></script>
        <!-- star rating plugin -->
        <script src="<?php echo $this->versioning('/admin/js/jquery.raty.min.js'); ?>"></script>
        <!-- for iOS style toggle switch -->
        <script src="<?php echo $this->versioning('/admin/js/jquery.iphone.toggle.js'); ?>"></script>
        <!-- autogrowing textarea plugin -->
        <script src="<?php echo $this->versioning('/admin/js/jquery.autogrow-textarea.js'); ?>"></script>
        <!-- multiple file upload plugin -->
        <script src="<?php echo $this->versioning('/admin/js/jquery.uploadify-3.1.min.js'); ?>"></script>
        <!-- history.js for cross-browser state change on ajax -->
        <script src="<?php echo $this->versioning('/admin/js/jquery.history.js'); ?>"></script>
        <!-- application script for Charisma demo -->
        <script>
            var url_satic='<?php echo STATIC_URL . '/admin/'; ?>';
        </script>
        <script src="<?php echo $this->versioning('/admin/js/charisma.js'); ?>"></script>
    </body>
</html>