<?php $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-type" content="text/html;charset=UTF-8">
        <?php $this->headTitle() ?>
        <?php $this->headMeta() ?>
        <?php $this->headLink() ?>

        <?php $this->headScript() ?>
        <?php $this->headStyle() ?>       
    </head>
    <body>
                <?php echo $this->layout()->content ?>

    </body>
</html>