<div class="box span12">
    <div class="box-header well" data-original-title>
        <h2>Actress List</h2>
    </div>
    <div class="box-content">
<a class="btn btn-small btn-primary" href="/admin/actress/new">New Actress</a>
<table class="table">
    <thead>
    <tr>
        <th>
            Name
        </th>
        <th>
            Status
        </th>
        <th>
            Description
        </th>
        <th>
            Img
        </th>
        <th>
            Options
        </th>
    </tr>
    </thead>
<?php foreach($this->listingActress as $index): ?>
    <tr>
        <td>
            <?php echo $index['actress_name']; ?>
        </td>
        <td>
            <?php if($index['actress_public'] == 1){ ?>
            <samp class="label label-success">Public</samp>
            <?php } else { ?>
            <samp class="label">Inactive</samp>
            <?php } ?>
        </td>
        <td>
            <?php echo $index['actress_description']; ?>
        </td>
        <td>
           <img width="50" height="50" src="<?php echo DINAMIC_URL . '/celebrity/mini/' . $index['actress_img']; ?>"/>
        </td>
        <td>
            <a class="btn btn-info" href="/admin/actress/up/id/<?php echo $index['actress_id']; ?>"><span class="icon-arrow-up icon-white"></span> Up</a>
            <a class="btn btn-info" href="/admin/actress/down/id/<?php echo $index['actress_id']; ?>"><span class="icon-arrow-down icon-white"></span> Down</a>
            <a class="btn btn-info" href="/admin/actress/edit/id/<?php echo $index['actress_id']; ?>"><span class="icon-edit icon-white"></span> Edit</a>
            <?php if($index['actress_public'] == 1){ ?>
            <a class="btn btn-info" href="/admin/actress/unpublish/id/<?php echo $index['actress_id']; ?>"><span class="icon-eye-close icon-white"></span> Unpublis</a>
            <?php } else { ?>
            <a class="btn btn-info" href="/admin/actress/publish/id/<?php echo $index['actress_id']; ?>"><span class="icon-eye-open icon-white"></span> Publish</a>
            <?php } ?>
        </td>
    </tr>
<?php endforeach; ?>
</table>
<?php
        echo $this->paginationControl($this->listingActress, 'Sliding', '/paginatorcontrol/actress.phtml');
        ?>
</div>
</div>