

<div class="affiliates-content" >
   	<h2 class="titulo_blanco">AFFILIATES</h2>
   	<p class="parrafos affiliates" >
   			<span class="subtitulos_gris" >JOIN THE WeTheAdorned AFFILIATE PROGRAM</span>
   			WeTheAdorned is thrilled to partner with websites and blogs on the vanguard of innovation in fashion, lifestyle, designer, and beauty
   	</p>

   	<h3 class="titulo_blanco" style="font-size: 32px;" >THE BENEFITS 
   	 <span class="subtitulo" >OF JOINING THE WeTheAdorned LINKSHARE AFFILIATE PROGRAM</span></h3>

   	<div class="listado" >
   			<ul>
   				<li>Competitive commission rates</li>
   				<li>Performance-based incentives</li>
   				<li>First look at product images from the latest exclusive collections</li>
   				<li>Advance notice of WeTheAdorned limited quantity releases</li>
   				<li>Access to WeTheAdorned ads</li>
   				<li>A dedicated affiliate team</li>
   			</ul>
   	</div>


	

</div>