

<div class="affiliates-content" >
   	<h2 class="titulo_blanco">AFFILIATES</h2>
   	<p class="parrafos affiliates" >
   			<span class="subtitulos_gris" >JOIN THE WeTheAdorned AFFILIATE PROGRAM</span>
   			WeTheAdorned is thrilled to partner with websites and blogs on the vanguard of innovation in fashion, lifestyle, designer, and beauty
   	</p>

   	<h3 class="titulo_blanco" style="font-size: 32px;" >THE BENEFITS 
   	 <span class="subtitulo" >OF JOINING THE WeTheAdorned LINKSHARE AFFILIATE PROGRAM</span></h3>

   	<div class="listado" >
   			<ul>
   				<li>Competitive commission rates</li>
   				<li>Performance-based incentives</li>
   				<li>First look at product images from the latest exclusive collections</li>
   				<li>Advance notice of WeTheAdorned limited quantity releases</li>
   				<li>Access to WeTheAdorned ads</li>
   				<li>A dedicated affiliate team</li>
   			</ul>
   	</div>

	<h3 class="titulo_blanco" style="font-size: 32px;" >ABOUT US </h3> 
   	<p class="parrafos" >	
   		Founded by T.Cyia designer’s Tim McElwee and Cyia Batten, WeTheAdorned is the only online pretailer to offer exclusive, limited quantity collections created by the best designers in the world —available immediately after they appear on our celebrity ambassadors for members only. With artistic direction by fashion visionary and street-style maven Cyia Batten, WeTheAdorned features such illustrious designers as Erickson Beamon, Luv AJ, Tom Tom, Pamela love, bliss lou, T.Cyia, and hundreds more. <br/><br/>
		For more information, please read our terms & conditions.

   	</p>




	

</div>