<?php 
    # Imprimimos el menu Change Section
    echo $this->partial('index/change_section.phtml', array('section'=>'CAMERON RICHARDSON BOUTIQUE', 'menu'=>$this->menu));
?>
    
<div id="contentBody" class="boutique">
    
    <div class="btns-options" >
        <a href="" class="btn addToCart" data-code="45">
            Add to my car
        </a>
        <a href="http://pinterest.com/pin/create/button/?url=http%3A%2F%2Fwetheadorned.com%2F&media=http%3A%2F%2Fdev.wetheadorned.com%2Fstatic%2Ffront%2Fimages%2FR_25.png" class="pin-it-button btn" count-layout="horizontal">Pin It</a>
    </div>
    
    <div  class="imgProd">
        <img src="<?php echo STATIC_URL . '/front/images/ivana-prod.jpg' ?>" />
    </div>
        
    <div class="info">
        <h1>
            <span class="name1">IVANA</span>
            <span class="name2">MILICEVIC</span>
        </h1>
        <h3><span class="linea-degr-left"></span>Article #9<span class="linea-degr-right"></span></h3>
        <h2>THE RESURRECTION</h2>
            
        <p>
            <strong>T.Cyia's</strong>  choker features two ram head skulls that kiss at the middle. It opens at the front and features a hinge mechanism at the back. It is made of bronze with a 24 kt gold plate or rose gold plate that has been E-coated to protect the integrity of its plating. The choker is 15" an the width of the horns when choker fully closed is 8" .
        </p>
            
        <div class="precios">
            <div>
                <span>Guest price</span>
                <strong class="inactivo">$699.00</strong>
            </div>
                
                
            <div >
                <span>member price</span>
                <strong class="activo">$475.00</strong>
            </div>
        </div>
            
    </div>
        
</div>

<?php 
    echo $this->partial('index/slider_products_boutique.phtml', array('data'=>$this->products, 'title'=>'ivana Milicevic BOUTIQUE'));
?>
    
<script>
    
    
</script>