<?php 
    # Imprimimos el menu Change Section
    echo $this->partial('index/change_section.phtml', array('section'=>'CAMERON RICHARDSON BOUTIQUE', 'menu'=>$this->menu));
    
    $name = explode(' ',$this->product['actress']['_name']);
    
?>
    
<div id="contentBody" class="boutique">
    
    <div class="btns-options" >
        <a href="" class="btn addToCart" data-code="<?php echo $this->product['_id']; ?>">
            Add to my cart
        </a>
        <a href="http://pinterest.com/pin/create/button/?url=http%3A%2F%2Fwetheadorned.com%2F&media=http%3A%2F%2Fdev.wetheadorned.com%2Fstatic%2Ffront%2Fimages%2FR_25.png" class="pin-it-button btn" count-layout="horizontal">Pin It</a>
    </div>
    
    <div  class="imgProd">
        <img src="<?php echo DINAMIC_URL.'/product/'.$this->product['images'][0]['image_name']; ?>" />
    </div>
        
    <div class="info">
        <h1>
            <span class="name1"><?php echo $name[0]; ?></span>
            <span class="name2"><?php echo $name[1]; ?></span>
        </h1>
        <h3><span class="linea-degr-left"></span>Article #<?php echo $this->product['_code']; ?><span class="linea-degr-right"></span></h3>
        <h2><?php echo $this->product['_name']; ?></h2>
            
        <p>
            <?php echo $this->product['_description']; ?>
        </p>
            
        <div class="precios">
            <div>
                <span>Guest price</span>
                <strong class="inactivo">$<?php echo number_format($this->product['_price'], 2); ?></strong>
            </div>


            <div >
                <span>member price</span>
                <strong class="activo">$<?php echo number_format($this->product['_priceMember'],2); ?></strong>
            </div>
        </div>
            
    </div>
        
</div>

<?php 
    echo $this->partial('index/slider_products_boutique.phtml', 
                                    array('data'=>$this->sliderProducts, 
                                                'title'=>$this->product['actress']['_name'].' BOUTIQUE',
                                                'url_base'=>$this->urlBase
                                        )
                                    );
?>
    
<script>
    
    
</script>