<?php 
    # Imprimimos el menu Change Section
    echo $this->partial('index/change_section.phtml', array('section'=>'Celebrity boutique'));
?>

<div id="contentBody" class="celebrity">
    <h1>Celebrity Boutique</h1>

    <div>
        
        <a href="">            
            <img src="<?php echo STATIC_URL ?>/front/images/cameron.jpg" />            
            <div>
                <span class="name name1">Cameron</span>
                <span class="name name2">Richardson</span>
                
                <span class="linea-degr-left"></span>
                VISIT BOUTIQUE
                <span class="linea-degr-right"></span>
            </div>
        </a>

        <a href="">
            <img src="<?php echo STATIC_URL ?>/front/images/melody.jpg" />
            <div>
                <span class="name name1">Cameron</span>
                <span class="name name2">Richardson</span>
                
                <span class="linea-degr-left"></span>
                VISIT BOUTIQUE
                <span class="linea-degr-right"></span>
            </div>
        </a>

        <a href="">
            <img src="<?php echo STATIC_URL ?>/front/images/ivana.jpg" />
            <div>
                <span class="name name1">Cameron</span>
                <span class="name name2">Richardson</span>
                
                <span class="linea-degr-left"></span>
                VISIT BOUTIQUE
                <span class="linea-degr-right"></span>
            </div>
        </a>
        
    </div>
    
</div>

<script>
    
    
</script>