<div id="change_section"><!-- CONTENT -->
    <span><?php echo $this->section; ?></span>
    <span class="submenu-btn">Change section</span>
    <div class="submenu-content">
        <ul>
            <li>
                <a href="" ><span>The Designers</span></a>
                <ul>
                    <li>
                        <span>TCYIA</span>
                        <span class="linea_separacion"></span>
                        <ul>
                            <li style="background: #FFF4"><a href="">ratter snakes</a></li>
                            <li style="background: #0FF4"><a href="">snakes intertwined</a></li>
                            <li style="background: #00F4"><a href="">rams</a></li>
                            <li style="background: #5554"><a href="">skulls</a></li>
                        </ul>
                    </li>
                    <li>
                        <span>LUVE AJ</span>
                        <span class="linea_separacion"></span>
                        <ul>
                            <li><a href="">ratter snakes</a></li>
                            <li><a href="">skulls</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li class="simple">
                <a href="" ><span>Exclusive Collections</span></a>
                <ul>
                    <li>
                        <a href="">Necklaces</a>
                    </li>
                    <li>
                        <a href="">bracelets</a>
                    </li>
                    <li>
                        <a href="">Rings</a>
                    </li>
                    <li>
                        <a href="">Earrings</a>
                    </li>
                </ul>
            </li>
            <li class="simple">
                <a href="" ><span>Celebrities Boutiques</span></a>        
                <ul>
                    <li>
                        <a href="">Cameron Richardson</a>
                    </li>
                    <li>
                        <a href="">Ivana Milicevic</a>
                    </li>
                    <li>
                        <a href="">Melody thornton</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="" ><span>Limited Quantity</span></a>
                <ul>
                    <li>
                        <a href="">ram ring</a>
                        <span class="linea_separacion"></span>
                        <ul>
                            <li>total quantity - 100</li>
                            <li>units left - 20</li>
                        </ul>
                    </li>
                    <li>
                        <a href="">Skull cuff</a>
                    </li> 
                </ul>
            </li>
            <li class="menGift">
                <a href="" ><span>Get a free gift today</span></a>
                <ul>
                    <li>
                        Become a <strong>member</strong> now!
                        <img src="<?php echo STATIC_URL?>/front/images/gift.png" />
                        <div class="linea_separacion"></div>
                        <div>                            
                            <span>BUY A WTA MEMBERSHIP AND<br/>
                            GET A FREE GIFT FOR YOU!</span>
                        </div>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>
<script>
    WTA.iniMenuSections();
</script>