
<div class="wLight" >
   <div class="comming_soon">
          <div class="contenido" >
                <div class="closex">X</div>
                <div class="titulo" >
                        COMING <div class="subtitulo" >SOON</div> 
                </div> 
                <div class="leyenda" >
                    We´re sorry for any inconvenience, please be patient as 
                    we work  on this  feature...
                </div>
          </div>

       

    </div>

</div>