<?php 
    # Imprimimos el menu Change Section
    echo $this->partial('index/change_section.phtml', array('section'=>'Designers', 'menu'=>$this->menu));
?>

<?php
    $categorys = $this->categorys;
    $category_active = $this->category_active;        
    
?>

<div id="change_category">
    <span>Choose another category</span>
    <select id="choosecat">
        <?php foreach($categorys as $cat): ?>
            <?php if ($category_active == strtolower($cat)){ ?>
                <option selected="selected " value="<?php echo $this->urlBase.urlencode(strtolower($cat));  ?>" ><?php echo $cat; ?></option>
            <?php }else{ ?>
                <option value="<?php echo $this->urlBase.urlencode(strtolower($cat));  ?>" ><?php echo $cat; ?></option>
            <?php } ?>
        <?php endforeach; ?>        
    </select>
</div>
<div  id="contentBody" class="designers" >        
    
    
    <div class="btns-options" >
        <a href="" class="btn addToCart" data-code="<?php echo $this->product['_id']; ?>">
            Add to my car
        </a>
        <a href="http://pinterest.com/pin/create/button/?url=http%3A%2F%2Fwetheadorned.com%2F&media=http%3A%2F%2Fdev.wetheadorned.com%2Fstatic%2Ffront%2Fimages%2FR_25.png" class="pin-it-button btn" count-layout="horizontal">Pin It</a>
    </div>
    
    <div  class="imgProd">
        <img src="<?php echo STATIC_URL.'/front/images/R_25.png' ?>" />
    </div>
    
    <div class="info">
        <h1><?php echo $this->product['designer']['_name']; ?></h1>
        <h3><span class="linea-degr-left"></span>Article #<?php echo $this->product['_code']; ?><span class="linea-degr-right"></span></h3>
        <h2><?php echo $this->product['_name']; ?></h2>
        
        <p>
           <?php echo $this->product['_descriptionDesigner']; ?>
        </p>
        
        <div class="precios">
            <div>
                <span>Guest price</span>
                <strong class="inactivo">$<?php echo number_format($this->product['_price'], 2); ?></strong>
            </div>


            <div >
                <span>member price</span>
                <strong class="activo">$<?php echo number_format($this->product['_priceMenber'],2); ?></strong>
            </div>
        </div>
        
    </div>
    
    
</div>

<?php 
    # Imprimimos el Slider de productos
    echo $this->partial('index/slider_products.phtml', 
                                   array('section'=>'Exclusive Collections', 
                                            'data'=>$this->sliderProducts , 
                                            'url_base'=>$this->urlBase, 
                                            'title'=>'luv aj’s SHARK TEETH  collection',
                                            'category'=>'design_type_name'
                                            ));
?>

<script>
    //WTA.Home();
    WTA.zoom('.imgProd');
</script>