<div class="wLight">
    <div id="forgotpass">
        <div>

            <form name="forgot" method="post">
                <h2>FORGOT YOUR PASSWORD?</h2>
                <span class="instrucciones">Enter your email address. We'll send you and email width a new password </span>
                <input type="text" name="email" placeholder="Email address"/>
                <input type="submit" value="SIGN IN" />

            </form>

        </div>

        <div class="closex">X</div>
    </div>
</div>