<?php 
    # Imprimimos el menu Change Section
    echo $this->partial('index/change_section.phtml', array('section'=>'Designers', 'menu'=>$this->menu));
?>

<?php
    $categorys = $this->categorys;
    $category_active = $this->category_active;        
    
?>

<div id="change_category">
    <span>BECOME A MEMBER TODAY  & start enjoying the BENEFITS OF MEMBERSHIP.</span>
</div>
<div  id="contentBody" class="designers" >        
    
    <div  class="imgProd">
        <img src="<?php echo STATIC_URL?>/front/images/free-gift.png" />
    </div>
    
    <div class="info">
        <h1>GET A FREE <br/>GIFT</h1>
        <h3><span class="linea-degr-left"></span>Article #00<span class="linea-degr-right"></span></h3>
        <h2>T.CYIA</h2>
        
        <a href="" class="details">Details</a>
        
        <div  class="details-content">
            <p>
                <strong>T.Cyia’s</strong> larger ram skull ring features horns that wrap around the finger, creating the top of two bands. Made of bronze with 24 kt gold plating this ring has been E-coated to protect the integrity of the finish.
                    Retail value: $99.00
            </p>
        </div>
        <div class="precios">
            <div>
                <span>REATIL VALUE</span>
                <strong class="activo">$99.00</strong>
            </div>
        </div>
        
        
        <div class="btns-options" >
            <a href="" class="btn big">
                BECOME A MEMBER NOW!
            </a>
        </div>
        
    </div>
    
    
</div>

<script>
    //WTA.Home();
    WTA.zoom('.imgProd');
</script>