<div id="contentBody">


    <div class="affiliates-content" >
        <h2 class="titulo_blanco">HOW IT WORKS</h2>
        <h3 class="titulo_blanco" style="font-size: 32px;" >IN-SEASON. EXCLUSIVE. LIMITED.</h3>
        <p class="parrafos affiliates" >
            WE OFFER MEMBERS THE MOST EXCLUSIVE JEWELRY COLLECTIONS FROM THE HOTTEST INDEPENDENT DESIGNERS CURATED BY THE WORLD’S MOST FASHIONABLE CELEBRITIES ….AT EXTRAORDINARY PRICES. 
How can we afford to do this?  Easy: we cut out the middleman. All he was doing was taking up space anyway. Let’s be honest, it’s 2013, if you aren’t over last season’s leftovers or paying retail prices – you should be.
        </p>

        <h3 class="titulo_blanco" style="font-size: 32px;" >WHY SHOULD I BECOME A MEMBER? </h3>
        <p class="parrafos affiliates">
            Good question. Despite lacking degrees from Harvard biz school, we think we’ve come up with an innovative idea to change the way sophisticated women like you shop for chic jewelry online….wait for it...we think that membership should ACTUALLY come with perks. That’s crazy, we know. Why didn’t the other guys think of that? Ask them. Why did we? Because you deserve perks. So, what kind of perks? Let’s dive in and we’ll tell you…
        </p>
        <p class="parrafos affiliates">
            ONLY MEMBERS HAVE ACCESS TO OUR EXCLUSIVE COLLECTIONS OFFERED AT EXTRAORDINARY PRICES WITH NO COMPROMISE ON QUALITY – EVER! 
        </p>
        <p class="parrafos affiliates">
            Every week we will launch a new series of limited quantity items from hottest independent designers but these pieces will only be available to you. So go ahead, Indulge your impulse and get adorned now: become a member and shop our exclusive limited quantity collections and they’ll ship today. 
        </p>
        <p class="parrafos affiliates">
            Our exclusive seasonal collections work differently. Anyone can shop the collections but only members have access to them at extraordinary prices. By placing a 50% deposit, you can pre-order the seasonal looks from our exclusive collections, offered by designers you already know, wear and love. 
        </p>
        
        <p class="parrafos affiliates">
            If you’re not a member, we can fix that. Shop our collections and let us seduce you with the additional benefits that membership has to offer.
        </p>
        
        <h3 class="titulo_blanco" style="font-size: 32px;" >YOU PIN IT. YOU SHARE IT. YOU GET REWARDED! </h3>
        <p class="parrafos affiliates">
            We are serious about rewarding our members. If you love an item, tell your friends about it by using your favorite social media outlet and we’ll reward you. By reward we mean CASH. Like, we pay you, our member…our newest affiliate (that has a cool ring to it). Seriously.  
            For more info see: <a href="/rewarding-our-members">Perks of Membership. </a>
        </p>
        
        <h3 class="titulo_blanco" style="font-size: 32px;" >YOUR ORDERS ARE  PRODUCED IN AMERICA. </h3>
        <p class="parrafos affiliates">
            Our designers produce each item from our exclusive seasonal collections for you within a 4-6 week period. Limited quantities ship immediately. Seasonal or limited, the production is always done right here in America. Always. We guarantee it.
        </p>
        
        <h3 class="titulo_blanco" style="font-size: 32px;" >YOU’VE BEEN ADORNED IN OUR LIMITED QUANTITY ITEM FOR WEEKS (YES, YOUR FRIENDS ARE SERIOUSLY JEALOUS) BUT WHAT ABOUT THAT SEASONAL ITEM YOU SELECTED?</h3>
        <p class="parrafos affiliates">
        When it is ready to ship, your remaining balance is processed and then your order is delivered to you in our signature, archival packaging. Now, go out and rock it like the sophisticated fashionista you are! 
        </p>
        

    </div>
</div>