<div  class="logo" >
    <img src="<?php echo STATIC_URL?>/front/images/wta.png"/>
    <p>
        Exclusive <span>Jewelry Collections</span> made only <br/>
        for you by the best designers in the world.
    </p>
</div>
<ul id="lissections">
    <li>
        <a href="" ><span>The Designers</span>
            <img src="<?php echo STATIC_URL?>/front/images/li_designers.png" />
        </a>

    </li>
    <li>
        <a href="" ><span>Exclusive Collections</span>
            <img src="<?php echo STATIC_URL?>/front/images/li_exlusivecollections.png" />                            
        </a>
    </li>
    <li>
        <a href="" ><span>Celebrities Boutiques</span>
            <img src="<?php echo STATIC_URL?>/front/images/li_celebritiesbboutiques.png" />                            
        </a>
    </li>
    <li>
        <a href="" ><span>Limited Quantity</span>
            <img src="<?php echo STATIC_URL?>/front/images/li_limitedquatity.png" />                            
        </a>
    </li>
    <li>
        <a href="" ><span>Get a free gift today</span>
            <img src="<?php echo STATIC_URL?>/front/images/li_gift.png" />                            
        </a>
    </li>
</ul>
<script>
    //WTA.Home();
    WTA.bgSlider(['<?php echo STATIC_URL?>/front/images/1girl.jpg', '<?php echo STATIC_URL?>/front/images/3girls.jpg'], '#bgslider')
</script>