<div id="contentBody"><!-- CONTENT -->
    <div  class="logo" >
        <img src="<?php echo STATIC_URL?>/front/images/wta.png" />
        <p>
            Exclusive <span>Jewelry Collections</span> made only <br/>
            for you by the best designers in the world.
        </p>
    </div>
    <ul id="lissections">
        <li>
            <a href="/designers" ><span>The Designers</span></a>
            <ul>
                <li>
                    <span>TCYIA</span>
                    <ul>
                        <li style="background: #FFF4"><a href="/designers">ratter snakes</a></li>
                        <li style="background: #0FF4"><a href="">snakes intertwined</a></li>
                        <li style="background: #00F4"><a href="">rams</a></li>
                        <li style="background: #5554"><a href="">skulls</a></li>
                    </ul>
                </li>
                <li>
                    <span>LUVE AJ</span>
                    <ul>
                        <li><a href="">ratter snakes</a></li>
                        <li><a href="">skulls</a></li>
                    </ul>
                </li>
            </ul>
        </li>
        <li>
            <a href="/exclusive-colletions" ><span>Exclusive Collections</span></a>
            <ul>
                <li>
                    <a href="">Necklaces</a>
                </li>
                <li>
                    <a href="">bracelets</a>
                </li>
                <li>
                    <a href="">Rings</a>
                </li>
                <li>
                    <a href="">Earrings</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="" ><span>Celebrities Boutiques</span></a>        
            <ul>
                <li>
                    <a href="">Cameron Richardson</a>
                </li>
                <li>
                    <a href="">Ivana Milicevic</a>
                </li>
                <li>
                    <a href="">Melody thornton</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="" ><span>Limited Quantity</span></a>
            <ul>
                <li>
                    <a href="">ram ring</a>
                    <ul>
                        <li>total quantity - 100</li>
                        <li>units left - 20</li>
                    </ul>
                </li>
                <li>
                    <a href="">Skull cuff</a>
                </li> 
            </ul>
        </li>
        <li class="menGift">
            <a href="" ><span>Get a free gift today</span></a>
            <ul>
                <li>
                    Become a <strong>member</strong> now!
                    <img src="<?php echo STATIC_URL?>/front/images/gift.png" />
                    <div class="linea_separacion"></div>
                    <div>
                        RENTAIL VALUE <strong>$99.00</strong>
                        <span>BUY A WTA MEMBERSHIP AND
                        GET A FREE GIFT FOR YOU!</span>
                    </div>
                </li>
            </ul>
        </li>
    </ul>
</div>
<script>
    WTA.Home();
    WTA.bgSlider(['<?php echo STATIC_URL?>/front/images/1girl.jpg', '<?php echo STATIC_URL?>/front/images/3girls.jpg'], '#bgslider')
</script>
