<?php 
    # Imprimimos el menu Change Section
    echo $this->partial('index/change_section.phtml', array('section'=>'Limited quantity', 'menu'=>$this->menu));
?>

<div  id="contentBody" class="limited" >
    
    <div  class="imgProd">
        <img src="<?php echo DINAMIC_URL.'/product/'.$this->product['images'][0]['image_name']; ?>" />
    </div>
    
    <div class="info">
        <h1><?php echo $this->product['_name']; ?></h1>
        <h3><span class="linea-degr-left"></span>Article #<?php echo $this->product['_code']; ?><span class="linea-degr-right"></span></h3>
        <h2><?php echo $this->product['designer']['_name']; ?></h2>
        
        <a href="" class="details">Details</a> /
        <a  class="available"><?php echo $this->product['_cantLimitedQuantity'] - $this->product['_cantBuy']?> units available to members only</a>
        
        <div  class="details-content">
            <p>
                <strong>T.CYIA</strong>  large cuff features a bright antique nickel shark tooth with oxidized nickel details. It sits atop an oxidized nickel cuff. 
    The cuff is 3 2/8" long, shark is 2.5" at widest and 3" long.
            </p>

            <div class="precios">
                <div>
                    <span>Guest price</span>
                    <strong class="<?php echo ($this->isMember) ? 'inactivo' : 'activo';?>">$<?php echo number_format($this->product['_price'], 2); ?></strong>
                </div>
                
                
                <div >
                    <span>member price</span>
                    <strong class="<?php echo (!$this->isMember) ? 'inactivo' : 'activo';?>">$<?php echo number_format($this->product['_priceMember'], 2); ?></strong>
                </div>
            </div>
            
        </div>
        
        <div class="btns-options" >
            <a href="" class="btn addToCart" data-code="<?php echo $this->product['_id']; ?>">
                Add to my cart
            </a>
            <a href="http://pinterest.com/pin/create/button/?url=http%3A%2F%2Fwetheadorned.com%2F&media=<?php echo urldecode(DINAMIC_URL.'/product/'.$this->product['images'][0]['image_name']); ?>" class="pin-it-button btn" count-layout="horizontal">Pin It</a>
        </div>
    </div>
    
    
    <a href="<?php echo $this->urlBase.$this->prev; ?>" class="prev3"></a>
    <a href="<?php echo $this->urlBase.$this->next; ?>" class="next3"></a>
    
</div>
<?php 
    # Imprimimos el menu Change Section
    //echo $this->partial('index/slider_products.phtml', array('section'=>'Limited Quantity Items', 'data'=>$this->products, 'title'=>'SPRING SUMMER COLLECTION'));
    echo $this->partial('index/slider_products.phtml', 
                                    array('section'=>'Limited Quantity Items', 
                                            'data'=>$this->sliderProducts, 
                                            'url_base'=>$this->urlBase, 
                                            'title'=>'Limited Quantity Items'
                                            ));

?>

<script>
    //WTA.Home();
    
    WTA.Exclusive();
    WTA.zoom('.imgProd');
</script>