<?php 
    # Imprimimos el menu Change Section
    echo $this->partial('index/change_section.phtml', array('section'=>'Limited quantity'));
?>

<div  id="contentBody" class="exclusive" >
    
    <div  class="imgProd">
        <img src="<?php echo STATIC_URL.'/front/images/R_25.png' ?>" />
    </div>
    
    <div class="info">
        <h1>ABELLONA</h1>
        <h3><span class="linea-degr-left"></span>Article #29<span class="linea-degr-right"></span></h3>
        <h2>T. CYIA</h2>
        
        <a href="" class="details">Details</a> /
        <a href="" class="details">SEE HOW MANY ITEMS ARE LEFT?</a>
        
        <div  class="details-content">
            <p>
                <strong>T.CYIA</strong>  large cuff features a bright antique nickel shark tooth with oxidized nickel details. It sits atop an oxidized nickel cuff. 
    The cuff is 3 2/8" long, shark is 2.5" at widest and 3" long.
            </p>

            <div class="precios">
                <div>
                    <span>Guest price</span>
                    <strong class="inactivo">$699.00</strong>
                </div>


                <div >
                    <span>member price</span>
                    <strong class="activo">$475.00</strong>
                </div>
            </div>
            
        </div>
        
        <div class="btns-options" >
            <a href="" class="btn addToCart" data-code="45">
                Add to my car
            </a>
            <a href="http://pinterest.com/pin/create/button/?url=http%3A%2F%2Fwetheadorned.com%2F&media=http%3A%2F%2Fdev.wetheadorned.com%2Fstatic%2Ffront%2Fimages%2FR_25.png" class="pin-it-button btn" count-layout="horizontal">Pin It</a>
        </div>
    </div>
    
    <a href="" class="prev3"></a>
    <a href="" class="next3"></a>
    
</div>
<?php 
    # Imprimimos el menu Change Section
    echo $this->partial('index/slider_products.phtml', array('section'=>'Exclusive Collections', 'data'=>$this->products, 'title'=>'SPRING SUMMER COLLECTION'));
?>

<script>
    //WTA.Home();
    
    WTA.Exlusive();
    WTA.zoom('.imgProd');
</script>