

<div class="rewarding-members-content" >
   	<h2 class="titulo_blanco">REWARDING OUR MEMBERS</h2>
   	<p class="parrafos members" >
   			WeTheAdorned places a serious emphasis on rewarding its members for referral memberships.

   	</p>
   	<h3 class="titulo_blanco" style="font-size:35px;" >WHAT ARE THE PERKS?</h3>
   	<p class="parrafos" >
   		<span class="subtitulos_gris" >Exclusive Access </span>Our limited quantity collections are reserved for MEMBERS ONLY.  That’s right.  When you see our celebrity partners rocking these collections, you can go out with confidence knowing that you, and only a handful of others like you, will be adorned in the same piece of jewelry!  We guarantee you won’t find these items anywhere else....and this isn’t a once a month thing -- every week WeTheAdorned will launch a new series of limited quantity pieces from the hottest independent designers so you always have something new to shop.
   	</p>
   	<p class="parrafos" >
   		<span class="subtitulos_gris" >Member Pricing </span> We give you an extraordinary item at an extraordinary price because you deserve it.  Forget retail and forget waiting for last season’s leftovers.  It’s 2013 and we’re changing the game for sophisticated fashionistas like you.  Our members have access to our seasonal, limited edition and limited quantity collections created by the designers you already know, wear and love at remarkable pricing, with no compromise on quality – ever.  Promise.
   	</p>

   	<p class="parrafos" >
   		<span class="subtitulos_gris" >Only Members get paid for sharing</span> If you love something you see on the site, tell your friends about it by using your favorite social media outlet and we’ll reward you with cash or points that can be applied to future purchases.  And this reward isn’t a couple of pennies here and there: we treat our member affiliates the same way we treat our editorial affiliates, which means that despite your having a smaller audience, we pay you the same percentage on commission: 5%.
   	</p>

   	 <p class="parrafos" >
   		<span class="subtitulos_gris" >Referral Rewards </span> Members will receive exclusive gifts for reaching certain referral milestones.  And the gifts won't be trinkets.  Ever!  We're talking great pieces from our exclusive collections -- pieces your friends will want but only members can have, pieces you'll be proud to rock!
   	</p>

   	 	<p class="parrafos" >
   		<span class="subtitulos_gris" >And don’t forget about the free gift</span> Sign up today and receive a free gift from the T.Cyia collection with a 3 month commitment. Retail value $
   	</p>


	

</div>