<div class="wLight">
    <div id="signin">
        <div>

            <form id="formSignin" action="/member/login" name="signin" method="post">
                <h2>SIGN IN</h2>
                <span class="instrucciones">Sign in with your WTA account</span>
                <label>                    
                    <input type="text" id="email" name="email" placeholder="Email address" class="" />
                </label>
                <label>
                    <input type="password" id="password" name="password"  placeholder="Password"   />
                <label>
                <!-- label><input type="checkbox" name="remember" value="1" /> Remember my session</labe l-->
                <input type="submit" value="SIGN IN" />

                <a class="forgot liLight" href="/index/forgotpass">FORGOT MY  <strong>PASSWORD</strong></a>
                
            </form>

        </div>

        <div>

            <form id="formRegister" action="/member/create-account" name="register" method="post">
                <h2>REGISTER</h2>
                <span class="instrucciones">Become a member</span>

                <div>
                    <input type="text" name="firstname" id="firstname" placeholder="First name" />                        
                    <input type="text" name="lastname" id="lastname" placeholder="Last name" />
                </div>

                <label>
                    <input type="text" name="email" id="email"  placeholder="Email address"  class="" />
                </label>

                <div>

                    <input type="password" name="password1" id="password1"  placeholder="Password"  class="" />
                    <input type="password" name="password2" id="password2"  placeholder="Confirm Password"   />
                </div>
                
                <label class="privacy">
                    <input type="checkbox" name="cbterms" id="cbterms" /> I have read and agreed to the Terms of Service.</a>
                </label>

                <input type="submit" value="JOIN" />
                
            </form>

        </div>
        <div class="closex">X</div>
    </div>
</div>
<script> 
    WTA.lightbox();
    WTA.signin();
</script>