<?php

    $_products = $this->data; 
    $_urlBase = $this->url_base; 

?>

<div id="slider_products"><!-- CONTENT -->

            <div class="bar">
                <span class="wetheadorned">wetheadorned.com</span>
                <span class="collectionsName"><?php echo $this->title ?></span>
            </div>
    
    <div class="slider-content">
        <div class="collectionsName">
            <span ><?php echo $this->title ?></span>
            <p>
                
            </p>            
        </div>
        <div id="slider-div">
            <ul id="slider">
                <?php if( !empty($_products) ): ?>
                    <?php foreach($_products as $product): ?>
                        <li>
                            <a href="<?php echo $_urlBase. 
                                                                    (empty($this->category) ? '' : urlencode(strtolower($product[$this->category])).'/')
                                                                    .$product['product_slug'] ?>">
                                <img src="<?php echo DINAMIC_URL.'/product/thumbs/'.$product['image']; ?>" />
                            </a>
                            <a href="<?php echo $_urlBase. 
                                                                    (empty($this->category) ? '' : urlencode(strtolower($product[$this->category])).'/')
                                                                    .$product['product_slug'] ?>" class="dsc">
                                <?php echo $product['product_code'] ? 'Item #'.$product['product_code'] : '' ; ?> 
                                <strong><?php echo $product['product_name']; ?></strong>
                                <span><?php echo $product['designer_name'] . ' - ' . $product['collection_type_name']; ?>  </span>
                            </a>
                        </li>
                    <?php endforeach; ?>
                <?php endif; ?>
                
            </ul>
            <a id="prev2" class="prev" href="#"></a>
            <a id="next2" class="next" href="#"></a>
        </div>
    </div>
</div>
<script>
    WTA.slider_products();
</script>