<div id="slider_products" class="boutique"><!-- CONTENT -->
    
    <div class="slider-content">
        <div class="collectionsName">
            <span ><?php echo $this->title ?></span>
            <p>
                Lorem ipsu dolor samed jasem duliam
            </p>            
        </div>
        <div id="slider-div">
            <ul id="slider">
                <li>
                    <a href="">
                        <img src="<?php echo STATIC_URL?>/front/images/thumb-slider.png" />
                        <div>
                            Item #luvaj5 <strong>Short shark tooth cuff</strong>
                            <span>LUV AJ - Oxidized brass detailing on a shiny </span>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="">
                        <img src="<?php echo STATIC_URL?>/front/images/thumb-slider.png" />
                        <div>
                            Item #luvaj5 <strong>Short shark tooth cuff</strong>
                            <span>LUV AJ - Oxidized brass detailing on a shiny </span>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="">
                        <img src="<?php echo STATIC_URL?>/front/images/thumb-slider.png" />
                        <div>
                            Item #luvaj5 <strong>Short shark tooth cuff</strong>
                            <span>LUV AJ - Oxidized brass detailing on a shiny </span>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="">
                        <img src="<?php echo STATIC_URL?>/front/images/thumb-slider.png" />
                        <div>
                            Item #luvaj5 <strong>Short shark tooth cuff</strong>
                            <span>LUV AJ - Oxidized brass detailing on a shiny </span>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="">
                        <img src="<?php echo STATIC_URL?>/front/images/thumb-slider.png" />
                        <div>
                            Item #luvaj5 <strong>Short shark tooth cuff</strong>
                            <span>LUV AJ - Oxidized brass detailing on a shiny </span>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="">
                        <img src="<?php echo STATIC_URL?>/front/images/thumb-slider.png" />
                        <div>
                            Item #luvaj5 <strong>Short shark tooth cuff</strong>
                            <span>LUV AJ - Oxidized brass detailing on a shiny </span>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="">
                        <img src="<?php echo STATIC_URL?>/front/images/thumb-slider.png" />
                        <div>
                            Item #luvaj5 <strong>Short shark tooth cuff</strong>
                            <span>LUV AJ - Oxidized brass detailing on a shiny </span>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="">
                        <img src="<?php echo STATIC_URL?>/front/images/thumb-slider.png" />
                        <div>
                            Item #luvaj5 <strong>Short shark tooth cuff</strong>
                            <span>LUV AJ - Oxidized brass detailing on a shiny </span>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="">
                        <img src="<?php echo STATIC_URL?>/front/images/thumb-slider.png" />
                        <div>
                            Item #luvaj5 <strong>Short shark tooth cuff</strong>
                            <span>LUV AJ - Oxidized brass detailing on a shiny </span>
                        </div>
                    </a>
                </li>
            </ul>
            <a id="prev2" class="prev" href="#"></a>
            <a id="next2" class="next" href="#"></a>
        </div>
    </div>
</div>
<script>
    WTA.slider_products();
</script>