<?php

    echo $this->partial('index/index.phtml', array('menu'=>$this->menu ));

?>

<div class="wLight popup">
    <div id="" class="">
        <!-- h1>let the fun begin</h1 --><br/><br/>
        <img src="<?php echo STATIC_URL?>/front-fase2/images/logo-degradado.png"><br/>
        <span class="linea_horiz"></span><br/><br/>
        <!-- p>
            if you have received an invite to have <strong> <em>access to a private preview of WTA,</em></strong> just enter your guest code below
        </p -->
        <form action="/beta/code/format/json" method="post" name="guestCode" id="guestCode">
            <input type="text" name="password" id="password" placeholder="Insert password" /><br/>
            <input type="submit" class=" btn-gris " style="vertical-align: super" value="ENTER" />
            <a href="/beta/welcome" class="liLight" data-top="40px"></a>
        </form>
    </div>
</div>

<script>
    WTA.beta();
    $(document).ready(function(){
        var $wLight = $('.wLight');
        $wLight.fadeIn();
        var left=257;
        $wLight.css({'margin-left': '-'+left+'px', top: '100px'});
        $('#overlay').css('background-color', '#000').show();
    })
</script>