<?php 
    # Imprimimos el menu Change Section
    //echo $this->partial('index/change_section.phtml', array('section'=>'Celebrity boutique', 'menu'=>$this->menu));
?>

<div id="contentBody" class="celebrity">
    <!-- h1>Celebrity Boutique</h1 -->
    <h1></h1>
    <div>

        <a href="/fase2/boutique/cameron-richardson">            
            <img src="<?php echo STATIC_URL ?>/front-fase2/images/cameron.jpg" />            
            <div>
                <span class="name name1">Cameron</span>
                <span class="name name2">Richardson</span>
                
                <span class="linea-degr-left"></span>
                SHOP BOUTIQUE
                <span class="linea-degr-right"></span>
            </div>
        </a>

        <a href="/fase2/boutique/melody-thornton">
            <img src="<?php echo STATIC_URL ?>/front-fase2/images/melody.jpg" />
            <div>
                <span class="name name1">Melody</span>
                <span class="name name2">Thornton</span>
                
                <span class="linea-degr-left"></span>
                SHOP BOUTIQUE
                <span class="linea-degr-right"></span>
            </div>
        </a>

        <a href="/fase2/boutique/ivana-milicevic">
            <img src="<?php echo STATIC_URL ?>/front-fase2/images/ivana.jpg" />
            <div>
                <span class="name name1">Ivana</span>
                <span class="name name2">Milicevic</span>
                
                <span class="linea-degr-left"></span>
                SHOP BOUTIQUE
                <span class="linea-degr-right"></span>
            </div>
        </a>
        
    </div>
    
</div>

<script>
    
    
</script>