<div class="box span12">
    <div class="box-header well" data-original-title>
        <h2>Product: <?php echo $this->name; ?></h2>
    </div>
    <div class="box-content">
        <a class="btn btn-small btn-primary" href="/admin/product/add-celebrity/product/<?php echo $this->product ?>">Add Celebrity</a>

        
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Status
                    </th>
                    <th>
                        commissions
                    </th>
                    <th>
                        Image
                    </th>
                    <th>
                        Options
                    </th>
                </tr>
            </thead>
            <?php
            $arrayLimited = array('No', 'Yes');
            foreach ($this->listingActrees as $index):
                ?>
                <tr>
                    <td>
    <?php echo $index['actress_name']; ?>
                    </td>
                    <td>
                        <?php if ($index['product_actress_active'] == 1) { ?>
                            <samp class="label label-success">Public</samp>
                        <?php } else { ?>
                            <samp class="label">Inactive</samp>
    <?php } ?>
                    </td>
                    
                    <td>
    <?php echo $index['product_actress_commission']; ?>
                    </td>
                    <td>
    <?php echo $index['product_actress_img']; ?>
                    </td>
                    <td>
                        
                        <?php if ($index['product_actress_active'] == 1) { ?>
                            <a class="btn btn-mini btn-info" href="/admin/product/unpublish-celebrity/product/<?php echo $this->product; ?>/id/<?php echo $index['product_actress_id']; ?>"><span class="icon-eye-close icon-white"></span> Unpublis</a>
                        <?php } else { ?>
                            <a class="btn btn-mini btn-info" href="/admin/product/publish-celebrity/product/<?php echo $this->product; ?>/id/<?php echo $index['product_actress_id']; ?>"><span class="icon-eye-open icon-white"></span> Publish</a>
                        <?php } ?>
                            <a class="btn btn-mini btn-info" href="/admin/product/edit-celebrity/product/<?php echo $this->product ?>/celebrity/<?php echo $index['product_actress_actress_id']; ?>"><span class="icon-edit icon-white"></span> Edit</a>
                            <a class="btn btn-mini btn-info" href="/admin/product/delete-celebrity/product/<?php echo $this->product ?>/celebrity/<?php echo $index['product_actress_actress_id']; ?>"><span class="icon-remove icon-white"></span> Eliminar</a>
                            
                            
                    </td>
                </tr>
        <?php endforeach; ?>
        </table>
<?php
        echo $this->paginationControl($this->listingActrees, 'Sliding', '/paginatorcontrol/product-celebrity.phtml',array('product'=>$this->product));
        ?>
    </div>
</div>
