<div class="box span12">
    <div class="box-header well" data-original-title>
        <h2>Product List</h2>
    </div>
    <div class="box-content">
        <a class="btn btn-small btn-primary" href="/admin/product/new">New Product</a>

        
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Code
                    </th>
                    <th>
                        Name
                    </th>
                    <th>
                        Status
                    </th>
                    <th>
                        Actress
                    </th>
                    <th>
                        Price
                    </th>
                    <th>
              Limited Quality
                    </th>
                    
                    <th>
                        Options
                    </th>
                </tr>
            </thead>
            <?php
            $arrayLimited = array('No', 'Yes');
            foreach ($this->listingProduct as $index):
                ?>
                <tr>
                    <td>
    <?php echo $index['product_code']; ?>
                    </td>
                    <td>
    <?php echo $index['product_name']; ?>
                    </td>
                    <td>
                        <?php if ($index['product_public'] == 1) { ?>
                            <samp class="label label-success">Public</samp>
                        <?php } else { ?>
                            <samp class="label">Inactive</samp>
    <?php } ?>
                    </td>
                    <td>
    <?php echo $index['product_actress']; ?>
                    </td>
                    <td>
    <?php echo $index['product_price']; ?>
                    </td>
                    <td>
    <?php echo $arrayLimited[$index['product_limited_quantity']].'<br>'; 
    if($index['product_limited_quantity']){
        echo 'Amount : '.(int)$index['product_cant_limited_quantity'].'<br>';
        echo 'Buy : '.(int)$index['product_cant_buy'];
    }
    
    ?>
                    </td>
                    <td>
                        <a class="btn btn-mini btn-info" href="/admin/product/up/id/<?php echo $index['product_id']; ?>"><span class="icon-arrow-up icon-white"></span> Up</a>
                        <a class="btn btn-mini btn-info" href="/admin/product/down/id/<?php echo $index['product_id']; ?>"><span class="icon-arrow-down icon-white"></span> Down</a>
                        <a class="btn btn-mini btn-info" href="/admin/product/edit/id/<?php echo $index['product_id']; ?>"><span class="icon-edit icon-white"></span> Edit</a><p></p>
                        <a class="btn btn-mini btn-info" href="/admin/product/celebrity/product/<?php echo $index['product_id']; ?>"><span class="icon-user icon-white"></span> Celebrity</a>
                            <a class="btn btn-mini btn-info" href="/admin/product/image/product/<?php echo $index['product_id']; ?>"><span class="icon-picture icon-white"></span> Image</a>
                        <?php if ($index['product_public'] == 1) { ?>
                            <a class="btn btn-mini btn-info" href="/admin/product/unpublish/id/<?php echo $index['product_id']; ?>"><span class="icon-eye-close icon-white"></span> Unpublis</a>
                        <?php } else { ?>
                            <a class="btn btn-mini btn-info" href="/admin/product/publish/id/<?php echo $index['product_id']; ?>"><span class="icon-eye-open icon-white"></span> Publish</a>
                        <?php } ?>
                            
                    </td>
                </tr>
        <?php endforeach; ?>
        </table>
<?php
        echo $this->paginationControl($this->listingProduct, 'Sliding', '/paginatorcontrol/product.phtml');
        ?>
    </div>
</div>
