<html>
    <head>
        <title>WeTheAdorned</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <style>            
            html{margin: 0}            
            table {border-collapse: collapse; border-spacing: 0;margin: 0;padding: 0;}
            th {font-weight: bold; vertical-align: bottom;margin: 0;padding: 0; border:0px;}
            td {font-weight: normal; vertical-align: top;margin: 0;padding: 0; border:0px; font-family: Arial, georgia, sans-serif ; color: #3b261c}
        </style>
    </head>
    <body>
        <div style=" background: #231f20; width: 100%">
            <table border="0" style="border-collapse: collapse; border-spacing: 0px " cellpadding="0" cellspacing="0" width="100%">
                <tr>
                    <td align ="center" style=" background: #231f20; ">
                        <img src="<?php echo STATIC_URL ?>/front-beta/images/order/header-order.jpg"  />
                    </td>
                </tr>
            </table>
        </div>
        <div style="  background: #FFF;  width:100%; padding: 0 30px">
            <table border="0" style="border-collapse: collapse; border-spacing: 0px " cellpadding="0" cellspacing="0"  width="100%">
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td style="font-size: 16px; padding: 0px 0px 10px 3px;">
                        Thank you for your order!
                    </td>
                </tr>                
                <tr>
                    <td style="background: #231f20; color:#FFF; padding: 2px 5px;">Order Information</td>
                </tr>
                <tr>
                    <td style="padding: 5px; font-size: 12px;">Merchant: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;WeTheAdorned</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td style="border-top: 2px solid #AAAAAA; background: #FFF; padding: 5px">
                        <table  border="0" style="border-collapse: collapse; border-spacing: 0px; width: 100%; font-size: 12px;" cellpadding="0" cellspacing="0" >                            
                            <tr>
                                <td>Billing Information</td>
                                <td>Shipping Information</td>
                            </tr>
                            <tr>
                                <td>JC</td>                                    
                                <td>Jc</td>
                            </tr>
                            <tr>
                                <td>JC</td>                                    
                                <td>Jc</td>
                            </tr>
                            <tr>
                                <td>JC</td>                                    
                                <td>Jc</td>
                            </tr>
                            <tr>
                                <td>JC</td>                                    
                                <td>Jc</td>
                            </tr>
                            <tr>
                                <td>JC</td>                                    
                                <td>Jc</td>
                            </tr>
                            <tr>
                                <td>JC</td>                                    
                                <td>Jc</td>
                            </tr>
                        </table>
                    </td>
                </tr>

                <tr>
                    <td>&nbsp;</td>
                </tr>

                <tr>
                    <td style="background: #FFF; padding: 12px; border-top: 2px solid #AAAAAA;">
                        <table  border="0" style="border-collapse: collapse; border-spacing: 0px; width: 100%; font-size: 12px;" cellpadding="0" cellspacing="0">                           
                            <tr>
                                <td style="width: 40px;">Item</td>
                                <td style="width: 100px;">Description</td>
                                <td style="width: 50px; text-align: center">Qty</td>
                                <td style="width: 50px; text-align: center">Taxable</td>                                    
                                <td style="width: 60px; text-align: right">Unit Price</td>
                                <td style="width: 60px; text-align: right">Item Total</td>
                            </tr>
                            <?php
                            if ($this->data['products']) {
                                foreach ($this->data['products'] as $prod) {
                                    ?>
                                    <tr>
                                        <td style="width: 40px;"><?php echo $prod['code'] ?></td>
                                        <td style=" width: 190px; text-align: left" ><?php echo $prod['_name'] ?></td>
                                        <td style=" width: 50px; text-align: center"> <?php echo $prod['quantity'] ?></td>
                                        <td style=" width: 40px; text-align: center">N</td>
                                        <td style="width: 40px; text-align: right">US $ <?php echo number_format($prod['finalPrice'],2) ?></td>
                                        <td style="width: 40px; text-align: right">US $ <?php echo number_format($prod['finalPrice']*$prod['quantity'],2) ?></td>
                                    </tr>
                                    <?php
                                }
                            }
                            ?>
                            <tr><td>&nbsp;</td></tr>                                                  
                            <tr>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td style="color: #333; font-size: 12px; font-weight: normal; text-align: right">Shipping:</td>
                                <td style="color: #333; font-size: 12px; font-weight: bold; text-align: right">$ <?php echo number_format($this->data['shipping_charge'], 2); ?></td>
                            </tr>                            
                            <tr>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td style="color: #333; font-size: 12px; font-weight: normal; text-align: right">Total:</td>
                                <td style="color: #333; font-size: 12px; font-weight: bold; text-align: right">$ <?php echo number_format($this->data['total'], 2); ?></td>
                            </tr>                            
                        </table>
                    </td>
                </tr>
                <tr>
                    <td style=" font-size: 12px;">
                        Transaction ID: &nbsp;&nbsp;&nbsp;&nbsp;<?php echo $this->data['transactionID']?>
                    </td>
                </tr>
            </table>
        </div>
        <br/><br/>
        <div style="  background: #231f20;  width:100%">
            <table border="0" style="border-collapse: collapse; border-spacing: 0px " cellpadding="0" cellspacing="0"  width="100%">
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td align ="center">
                        <img src="<?php echo STATIC_URL ?>/front-beta/images/order/info-wetheadorned-com.jpg"  />
                    </td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
            </table>
        </div>
        
    </body>
</html>