
<div class="wLight" >
   <div  id="processed" class="popup">
          <div class="" >
                <div class="closex">X</div>
                <h1>
                        CONGRATULATIONS
                </h1> 
                <br/>
                <p>
                    Your order has been<br/>
                    processed for one of our<br/>
                    limited quantity selections. <br/>
                    Please check your<br/>
                    email for our receipt.<br/><br/>
                    Have a fantastic day!
                </p>
                <!-- a href="" class="btn btn-negro">Continue</a -->
          </div>

       

    </div>

</div>
