<?php

    echo $this->partial('index/index.phtml', array('menu'=>$this->menu ));

?>

<div class="wLight">
    <div id="passbeta" class="contenido">
        <h1>let the fun begin</h1>
        <span class="linea_horiz"></span>
        <p>
            if you have received an invite to have <strong> <em>access to a private preview of WTA,</em></strong> just enter your guest code below
        </p>
        <form action="/beta/code/format/json" method="post" name="guestCode" id="guestCode">
            <input type="text" name="password" id="password" placeholder="Insert Guest Code" />
            <input type="submit" value="SIGN IN" />
            <a href="/beta/welcome" class="liLight" data-top="40px"></a>
        </form>        
    </div>
</div>

<script>
    WTA.beta();
    $(document).ready(function(){
        var $wLight = $('.wLight');
        $wLight.fadeIn();
        var left=257;
        $wLight.css({'margin-left': '-'+left+'px', top: '100px'});        
        $('#overlay').fadeIn();   
    })
</script>