
<div class="wLight">
    <div id="welcomebeta" class="contenido">
        <div>
            <h1>You made it! <br/>Let the fun begin</h1>
            <span class="linea_horiz"></span>
            <p class="principal">
                Welcome to your private preview of <strong><em>WeTheAdorned:</em></strong> the most exclusive online collection of the hottest independent jewelry designs, curated by the world’s most fashionable celebrities.  
            </p>
            <p>
                Are you enjoying the gift we sent? If you didn’t receive one, you should have -- email us and we’ll take care of it).  As we continue preparing for our official launch, here’s how the next couple months are going to work: if you received an invitation -- you’re in.  
            </p>
            <p>
                We’ve taken care of the membership fee. Start shopping the exclusive and limited quantity collections you won’t find anywhere else and watch closely as more of the designers you already know, wear and love begin to appear. So go ahead,  enjoy all the benefits of membership. Get adorned...You know you want to!
            </p>
        </div>
        <span class="closex">X</span>
    </div>    
</div>
