<?php if ($this->pageCount): ?>
        <div class="dataTables_info">   <?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?>
            of <?php echo $this->totalItemCount; ?> Total
        </div>

    <div class="span12 center">
    <div class="dataTables_paginate paging_bootstrap pagination">
        
        <ul>
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
        <?php if($this->search==''){ ?>
            <li class="prev"><a  href="/admin/menbers?page=<?php echo $this->previous; ?>">
        <?php } else { ?>            
            <li class="prev"><a  href="/admin/menbers?search=<?php echo $this->search; ?>&page=<?php echo $this->previous; ?>">                         
        <?php }  ?>            
                &lt; Previous
            </a></li>
        <?php else: ?>
            <li class="prev"><a  >&lt; Previous</a></li>
        <?php endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
        <?php if($this->search==''){ ?>
                <li><a href="/admin/menbers?page=<?php echo $page ?>">
         <?php } else { ?>            
            <li class="prev"><a  href="/admin/menbers?search=<?php echo $this->search; ?>&page=<?php echo $page; ?>">                         
        <?php }  ?>                 
                    <?php echo $page; ?>
                </a></li>
            <?php else: ?>
                <li class="active"><a ><?php echo $page; ?> </a></li>
            <?php endif; ?>
        <?php endforeach; ?>
        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
        <?php if($this->search==''){ ?>
            <li class="nex"><a   href="/admin/menbers?page=<?php echo $this->next; ?>">
          <?php } else { ?>            
            <li class="prev"><a  href="/admin/menbers?search=<?php echo $this->search; ?>&page=<?php echo $this->next; ?>">                         
        <?php }  ?>            
                Next &gt;
            </a></li>
        <?php else: ?>
            <li class="nex"><a  class="disabled">Next &gt;</a></li>
        <?php endif; ?>
            </ul>
    </div>
    </div>
<?php endif; ?>

