
<div class="wLight" >
   <div  id="processed" class="popup">
          <div class="" >
                <div class="closex">X</div>
                <h1>
                        BEFORE YOU GO...
                </h1> 
                <br/>
                <form id="susbcriptions" name="susbcriptions" >
                    <input type="text" value="" placeholder="name@email.com" name="input_suscription" id="input_suscription"/>
                </form>
                
                <p class="small">
                    Sign up for daily reminds and be entered to win a 24kt. gold mystery gift offered exclusively to our registered users every month. <br/>
                    And unlike the other guys, we’ll never share your email address. You’re privacy is our priority. Guaranteed. Get adorned!
                </p>
                <a href="" class="btn btn-negro" id="saveSubscription">Continue</a>
          </div>

    </div>
</div>
<script>
    WTA.initFormSubscriptions();
</script>