<div <?php echo !$this->visible ? 'class="wLight"' : 'id="contentBody"'?>>

    <div class="popup large patron-lineas " id="membership">
        <?php echo !$this->visible ? '<div class="closex">X</div>' : ''?>
        <div >
            <!-- h2 class="">HOW IT WORKS</h2-->
            <img src="<?php echo STATIC_URL ?>/front-fase2/images/logo-degradado.png" />
            <h1 ><img src="<?php echo STATIC_URL ?>/front-fase2/images/texts/benefits-of-membership.png" /></h1>

            <p >
It’s simple. Forget the race to the bottom of the quality curve, our goal was to create a platform for independent jewelry designers that would allow them to sell their BEST pieces, the pieces that allow them to continue to GROW and ENHANCE their brands in volume (unlike our competitors). By paying a membership fee you are all collectively helping us protect the integrity of the brands we represent while helping them earn a living doing what they love: adorning you!
            </p>
            <br/>
            <a href="/fase2/membership" class="btn btn-amarillo">JOIN AND COMPLETE FOLIO</a>
        </div>
    </div>
</div>