<div <?php echo !$this->visible ? 'class="wLight"' : 'id="contentBody"'?>>

    <div class="popup big patron-lineas " id="membership">
        <?php echo !$this->visible ? '<div class="closex">X</div>' : ''?>
        <div >
            <!-- h2 class="">HOW IT WORKS</h2-->
            <img src="<?php echo STATIC_URL ?>/front-fase2/images/logo-degradado.png" />
            <h1 ><img src="<?php echo STATIC_URL ?>/front-fase2/images/texts/benefits-of-membership.png" /></h1>

            <?php echo $this -> content["content_body"]; ?>
            <br/>
            <a href="/fase2/membership?f=1" class="btn btn-amarillo">JOIN AND COMPLETE FOLIO</a>
        </div>
    </div>
</div>