<div <?php echo !$this->visible ? 'class="wLight"' : 'id="contentBody"'?>>

    <div class="popup big patron-lineas " id="membership">
        <?php echo !$this->visible ? '<div class="closex">X</div>' : ''?>
        <div >
            <!-- h2 class="">HOW IT WORKS</h2-->
            <img src="<?php echo STATIC_URL ?>/front-fase2/images/logo-degradado.png" />
            <h1 >Coming Soon</h1>
            <br/>
            <div style="padding: 0px 30px;"><?php echo $this -> content["content_body"]; ?></div>
            <br/>
        </div>
    </div>
</div>