<div <?php echo !$this->visible ? 'class="wLight"' : 'id="contentBody"'?>>
        
    <div class="popup gradient radial patron-lineas howit-content ">
        <?php echo !$this->visible ? '<div class="closex">X</div>' : ''?>
        <div class="patron scrollbar" >            
            <!-- h2 class="">HOW IT WORKS</h2-->
            <h2 class=""><img src="<?php echo STATIC_URL;?>/front-fase2/images/texts/how-it-works.png"</h2>
            <h3 >IN-SEASON. EXCLUSIVE. LIMITED. </h3>
            <p >
                We offer members the most exclusive jewelry collections from the hottest independent designers currated by the world’s most fashionable celebrities….AT EXTRAORDINARY PRICES. 
It’s 2013, if you aren’t over last season’s leftovers or paying retail prices – you should be.

            </p>
            
            <h3 >
                WHY SHOULD I BECOME A MEMBER? 
            </h3>
            <p >
                Good question. Despite lacking degrees from Harvard biz school, we think we’ve come up with an innovative idea to change the way sophisticated women like you shop for chic jewelry online -- we think that membership should ACTUALLY come with perks. So, what kind of perks?
            </p>
            
            <h3 >
                ONLY MEMBERS HAVE ACCESS TO OUR EXCLUSIVE COLLECTIONS OFFERED AT EXTRAORDINARY PRICES!
            </h3>
            <p >
                Every week we will launch a new series of limited quantity items from hottest independent designers but these pieces will only be available to you. So go ahead, Indulge your impulse and get adorned now and your item will ship today. 
            </p>            
            <p >
                Our exclusive seasonal collections work differently. Anyone can shop the collections but only members have access to them immediately and at extraordinary prices. 
            </p>            
            <p >
                By placing a 50% deposit, non-members can pre-order the seasonal looks from our exclusive collections…but who wants to wait 8 weeks for something you could have tomorrow.
            </p>
            </h3>
            <p >
                If you’re not a member, we can fix that. Shop our collections and let us seduce you with the additional benefits that membership has to offer.
            </p>
            <p >
                Oh, and btw…
            </p>
            
            <h3 >
                YOUR ORDERS ARE  PRODUCED IN AMERICA. 
            </h3>
            <p >
                Now, go out and rock it like the sophisticated fashionista you are!
            </p>
            

        </div>
    </div>
</div>