<div <?php echo !$this->visible ? 'class="wLight"' : 'id="contentBody"'?>>
        
    <div class="popup gradient radial patron-lineas howit-content ">
        <?php echo !$this->visible ? '<div class="closex">X</div>' : ''?>
        <div class="patron scrollbar" >            
            <!-- h2 class="">HOW IT WORKS</h2-->
            <h2 class=""><img src="<?php echo STATIC_URL;?>/front-fase2/images/texts/how-it-works.png"</h2>
            <?php echo $this -> content["content_body"]; ?>
        </div>
    </div>
</div>