<div <?php echo !$this->visible ? 'class="wLight"' : 'id="contentBody"'?>>

    <div class="popup big patron-lineas " id="membership">
        <?php echo !$this->visible ? '<div class="closex">X</div>' : ''?>
        <div >
            <!-- h2 class="">HOW IT WORKS</h2-->
            <img src="<?php echo STATIC_URL ?>/front-fase2/images/logo-degradado.png" />
            <h1 ><img src="<?php echo STATIC_URL ?>/front-fase2/images/texts/why-join.png" /></h1>

            <p >
                Wetheadorned is the first membership site that truly provides real benefits to becoming a member.
            <br/>
                Our Exclusive folio members…
            <br/>
                Enjoy insider pricing
            <br/>
                Receive exclusive access to limited quantity collections
            <br/>
                Get paid for new member referral and sales
            <br/>
                Get adorned!
            </p>
            <br/>
            <a href="/fase2/membership?f=1" class="btn btn-amarillo">JOIN AND COMPLETE FOLIO</a>
        </div>
    </div>
</div>