<div class="box span12">
    <div class="box-header well" data-original-title>
        <h2>Designer List</h2>
    </div>
    <div class="box-content">
<a class="btn btn-small btn-primary" href="/admin/designer/new">New Designer</a>
<table class="table">
    <thead>
    <tr>
        <th>
            Name
        </th>
        <th>
            Status
        </th>
        <th>
            Description
        </th>
        <!--
        <th>
            Img
        </th>
        -->
    </tr>
    </thead>
<?php foreach($this->listing as $index): ?>
    <tr>
        <td>
            <?php echo $index['designer_name']; ?>
        </td>
        <td>
            <?php if($index['designer_public'] == 1){ ?>
            <samp class="label label-success">Public</samp>
            <?php } else { ?>
            <samp class="label">Inactive</samp>
            <?php } ?>
        </td>
        <td>
            <?php echo $index['designer_description']; ?>
        </td>
        <!--
        <td>
           <img  src="<?php echo DINAMIC_URL . '/designer/mini/' . $index['designer_image']; ?>"/>
        </td>
        -->
        <td>
            <a class="btn btn-mini btn-info" href="/admin/designer/edit/id/<?php echo $index['designer_id']; ?>"><span class="icon-edit icon-white"></span> Edit</a>
            <a class="btn btn-mini btn-info btn-setting deleteAction" id="deleteAction" href="/admin/designer/delete/id/<?php echo $index['designer_id']; ?>"><span class="icon-trash icon-white"></span> Delete</a>
            <?php if($index['designer_public'] == 1){ ?>
            <a class="btn btn-mini btn-info" href="/admin/designer/unpublish/id/<?php echo $index['designer_id']; ?>"><span class="icon-eye-close icon-white"></span> Unpublish</a>
            <?php } else { ?>
            <a class="btn btn-mini btn-info" href="/admin/designer/publish/id/<?php echo $index['designer_id']; ?>"><span class="icon-eye-open icon-white"></span> Publish</a>
            <?php } ?>
        </td>
    </tr>
<?php endforeach; ?>
</table>
<?php
        echo $this->paginationControl($this->listing, 'Sliding', '/paginatorcontrol/designer.phtml');
        ?>
</div>
</div>



<div class="modal hide fade" id="myModal">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3>Delete</h3>
    </div>
    <div class="modal-body">
        Want to remove this designer
    </div>
    <div class="modal-footer">
        <a href="#" class="btn" id="yesDelete" data="X" data-dismiss="modal">Yes</a>
        <a href="#" class="btn" data-dismiss="modal">No</a>
    </div>
</div>