<div id="contentBody">
<div class="aWraper">
<div class="aBack">
    <div id="image_mujer" >
    <img src="/static/front/images/cyia-tim.jpg">
    </div>

    <div class="secondCol">
        <div>KNOW MORE ABOUT US</div>
        <div>
            <div clasS="torres_float" >
                <div>CYIA <span>BATTEN</span></div><br/>
                Founded by T.Cyia designer’s Tim McElwee and Cyia Batten, WeTheAdorned is the only online pretailer to offer exclusive, limited quantity collections created by the best designers in the world —available immediately after they appear on our celebrity ambassadors for members only. With artistic direction by fashion visionary and street-style maven Cyia Batten,                 
            </div>

            <div clasS="torres_float" >
                <div>TIM <span>MCELWEE</span></div><br/>
                Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad.

minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum i.
            </div>
        </div>
    </div>
</div>

</div>
</div>