<div class="wLight">
    <div class="wContact">

        <div>
            <div>
                <div>CONTACT US<div></div></div>

                <div class="contactBox">
                    <div>INFORMATION</div>
                    info@wetheadorned.com
                </div>
                <div class="contactBox">
                    <div>CAREER INQUIRIES</div>
                    careers@wetheadorned.com
                </div>
                <div class="contactBox">
                    <div>CUSTOMER CARE</div>
                    care@wetheadorned.com

                </div>
                <div class="contactBox">
                    <div>DESIGNER INQUIRIES</div>
                    designers@wetheadorned.com
                </div>
                <div class="contactBox">
                    <div>PERSONAL STYLISTS</div>
                    stylist@wetheadorned.com

                </div>
                <div class="contactBox">
                    <div>TECHNICAL SUPPORT</div>
                    support@wetheadorned.com
                </div>
                <div class="contactBox">
                    <div>PRESS INQUIRIES</div>
                    press@wetheadorned.com

                </div>
                <div class="contactBox">
                    <div>AFFILIATE PROGRAM INQUIRIES</div>
                    press@wetheadorned.com
                </div>

            </div>
        </div>
        <div><img src="/static/front/images/alone-girl.png" width="177px"></div>
        <div class="closex">X</div>
    </div>
</div>