
<div class="wLight">

    <div class="sAbout">
        <div class="closex">X</div>
        <div>
            <p>
                <span>ABOUT WE THE ADORNED</span><br/>
                <br/>
                Fashion jewelry designers Tim McElwee and Cyia Batten joined forces in 2004 to create the coveted jewelry line T.Cyia that has been featured on celebs and style icons worldwide. They’re at it again with a dynamic vision to change the way designers and fashion aficionados worldwide shop for and purchase jewelry online. Launched in Hollywood, California in February 2013, WeTheAdorned offers members the most exclusive online collection of the hottest independent jewelry designs curated by the world’s most fashionable celebrities.  In the trenches, working with the best independent designers, the WTA team is changing the online retail game for its members, stylists and designers by offering these exclusive, limited quantity collections at EXTRAORDINARY prices with no compromise on quality -- EVER! That’s our member guarantee. Everything on our site will be seasonal and exclusive.  You won’t find our collections anywhere else. <br/><br/>
                Contact your Personal Stylist:
                Via email: <a href="mailto:stylists@wetheadorned.com">stylists@wetheadorned.com</a>
            </p>            
            <!-- a href="/about-us" class="leer_mas">learn more about us</a -->
        </div>
    </div>

</div>