<div class="box span12">
    <div class="box-header well" data-original-title>
        <h2>Actress List</h2>
    </div>
    <div class="box-content">
        <form method="get" >
            Search: <input type="text" id="search" name="search"/>
        </form>
<table class="table">
    <thead>
    <tr>
        
        <th>
            Name
        </th>
        <th>
            Status
        </th>
        <th>
            mail
        </th>
        <th>
            Options
        </th>
    </tr>
    </thead>
<?php foreach($this->listingMember as $index): ?>
    <tr>
        
        <td>
            <?php echo $index['member_name']; ?>
        </td>
        <td>
            <?php if($index['member_active'] == 1){ ?>
            <samp class="label label-success">Active</samp>
            <?php } else { ?>
            <samp class="label">Inactive</samp>
            <?php } ?>
        </td>
        <td>
            <?php echo $index['member_mail']; ?>
        </td>
        <td>
            <?php if($index['member_active'] == 1){ ?>
            <a class="btn btn-info" href="/admin/members/inactive/id/<?php echo $index['member_id']; ?>"><span class="icon-eye-close icon-white"></span> Inactive</a>
            <?php } else { ?>
            <a class="btn btn-info" href="/admin/members/active/id/<?php echo $index['member_id']; ?>"><span class="icon-eye-open icon-white"></span> Active</a>
            <?php } ?>
            <a class="btn btn-info" href="/admin/orders?menbers%5B%5D=<?php echo $index['member_id']; ?>"><span class="icon-shopping-cart icon-white"></span> View Orders</a>
           </td>
    </tr>
<?php endforeach; ?>
</table>
<?php
        echo $this->paginationControl($this->listingMember, 'Sliding', '/paginatorcontrol/members.phtml',array('search'=>$this->search));
        ?>
</div>
</div>