<?php 

    $total = 0;
    $nprod = count($this->cart);
    if($nprod){
        foreach($this->cart as $prod){
            if($this->isMember){
                $total += $prod['_priceMember'] * (int)$prod['quantity'];
            }else{
                $total += $prod['_price'] * (int)$prod['quantity'];
            }
?>

            <div class="prod"><!-- PRODUCT -->

                <div class="prices">
                    <div>Guest price <strong class="<?php echo ($this->isMember) ? 'prec1' : 'prec2';?>"><br/>$<?php echo number_format($prod['_price'] * (int)$prod['quantity'],2) ?></strong></div>
                    <div>Member price <strong class="<?php echo (!$this->isMember) ? 'prec1' : 'prec2'; ?>"><br/>$<?php echo number_format($prod['_priceMember'] * (int)$prod['quantity'],2) ?></strong></div>                                        
                </div>

                <img src="<?php echo DINAMIC_URL.'/product/mini/'.$prod['images'][0]['image_name']; ?>" />

                <div class="info">
                    <span class="name">Item #<?php echo $prod['_code']; ?><strong> <em><?php echo $prod['_name']; ?></em></strong></span>
                    <span class="dsc"><?php echo $prod['designer']['_name']; ?></span>
                </div>

                <div class="controls">
                    <label class="size" >
                    <?php 
                        if( !empty($prod['sizes']) ){
                    ?>
                            SIZE 
                            <select class="products_size">
                                <?php
                                    foreach($prod['sizes'] as $size){
                                        if( $prod['size_prod'] ==  $size['product_size_size_id'] ){
                                            echo '<option selected="selected" value="'.$size['product_size_size_id'].'">'.$size['size_name'].'</option>';
                                        }else{
                                            echo '<option value="'.$size['product_size_size_id'].'">'.$size['size_name'].'</option>';
                                        }
                                    }
                                ?>
                                </select>
                    <?php
                        }                    
                    ?>                            
                    </label>
                    <label class="quantity">QTY <input type="text" data-code="<?php echo $prod['clave'] ?>" name="quantity" class="quantity" value="<?php echo (int) (isset($prod['quantity']) ? $prod['quantity'] : 1); ?>" /></label>
                    <a href="/shopping/removeitem/clave/<?php echo $prod['clave'] ?>/format/json" class="remove" >remove</a>
                </div>

            </div>
<?php 
        }
?>
  
    <div class="rowtotal">
        <span>Subtotal</span>
        <span class="ntotal">$<?php echo number_format($total,2); ?></span>
        <a href="/checkout" class="checkout btn" >Check out</a>
    </div>      
<?php
    }else{
        
    }

/*
<div class="prod"><!-- PRODUCT -->

    <div class="prices">
        <div>Guest price <strong class="prec1"><br/>$526.00</strong></div>
        <div>Member price <strong class="prec2"><br/>$288.00</strong></div>                                        
    </div>

    <img src="<?php echo STATIC_URL . '/front/images/sp_prod2.png'; ?>" title="" alt="" />

    <div class="info">
        <span class="name">Item #R9 <strong><em>Abellona</em></strong></span>
        <span class="dsc">T.CYIA - bronze & 24kt Gold Plate</span>
    </div>

    <div class="controls">
        <label class="size">SIZE <select ><option>7 1/2</option></select></label>
        <label class="quantity">QTY <input type="text" name="quantity" value="1" /></label>
        <a href="" class="remove" >remove</a>
    </div>

</div>
*/  ?>