<?php




    # Imprimimos el menu Change Section
    //echo $this->partial('index/change_section.phtml', array('section'=>'Designers', 'menu'=>$this->menu));
?>

<div  id="contentBody" class="checkout" >

    <div >

        <div class="imgPrincipal">
            <img src="<?php echo STATIC_URL . '/front-fase2/images/specials/melody.jpg';?>" />
        </div>

        <!-- FORM CHECKOUT -->
        <?php
            echo $this->partial('shopping/formCheckout.phtml', array('cart'=>$this->cart, 'shipping'=>$this->shipping, 'cartMembership'=>$this->cartMembership , 'shippingAddress'=>$this->shippingAddress, 'billingInformation'=>$this->billingInformation, 'invitation'=>$this->invitation));
        ?>

    </div>

    <div id="checkout-cart">
        <?php
            echo $this->partial('shopping/checkoutcart.phtml', array('cart'=>$this->cart, 'shipping'=>$this->shipping, 'cartMembership'=>$this->cartMembership));
        ?>
    </div>

</div>
<a href="/fase2/order/processed" class="liLight" id="linkprocessed"></a>
<a href="/fase2/order/error" class="liLight" id="linkerror"></a>
<a href="/fase2/before-you-go" id="checkoutcancel" ></a>

<script>
    //WTA.initElementsById(<?php echo json_encode($this->cartMembership); ?>);
    //WTA.updateCart();
    WTA.membership();
    WTA.checkoutForm();
    WTA.abandon();


    $(document).ready(function(){
        $('.remove').click(function(e){
            e.preventDefault();
            $.ajax({
                url: $(this).attr('href')
            }).done(function(response){
                WTA.updateCart();
            });
        });

    })

</script>