
<div class="wLight no-border" >
   <div class="comming_soon" id="processed">
          <div class="contenido" >
                <div class="closex">X</div>
                <h1>
                        YOUR ORDER HAS<br/>
                        BEEN PROCESSED
                </h1> 
                <br/>
                <p>
                    Thanks you for placing your order. We  will be in contact soon. So what happens now?
                </p>
                <br/>
                <ul>
                    <li>- You will shortly receive an email containing the details of your order.</li>
                    <li>- LoremIpsu dolor shipping consectetuer adipiscing elit, sed diam non.</li>
                </ul>
          </div>

       

    </div>

</div>