<div class="wLight">
    <div id="forgotpass" class="contenido">
        <div>

            <form name="forgot"  id="forgot" action="/member/recovery-account/recovery" method="post">
                <h2>FORGOT YOUR PASSWORD?</h2>
                <span class="instrucciones">Enter your email address. We'll send you and email width a new password </span>
                <input type="text" name="mail" placeholder="Email address"/>
                <input type="submit" value="GO" />

            </form>

        </div>

        <div class="closex">X</div>
    </div>
</div>
<script>
    WTA.ForgotPassword();
</script>