<div class="wLight">
    <div id="signin" class="popup">
        <div>

            <form name="forgot"  id="forgot" action="/member/recovery-account/recovery" method="post">
                <h1>FORGOT YOUR PASSWORD?</h1>
                <p>
                    Enter your email address. <br/>We'll send you and email <br/>with a new password 
                </p>
                <input type="text" name="mail" placeholder="Email address"/>
                <br/>
                <a class="btn btn-negro submit" href="">Go</a><br/>

            </form>

        </div>

        <div class="closex">X</div>
    </div>
</div>
<script>
    WTA.ForgotPassword();
</script>