<div class="wLight">
    <div id="reserved4members" class="popup wide">
        <div>
            <h1><img src="<?php echo STATIC_URL ?>/front-fase2/images/texts/reserved-for-members.png" /></h1>
            
            <form id="formSignin" action="/member/login" name="signin" method="post">                
                <h2>Welcome back <br/>login</h2>
                <label>                    
                    <input type="text" id="email" name="email" placeholder="Email address" class="" />
                </label>
                <label>
                    <input type="password" id="password" name="password"  placeholder="Password"   />
                </label>

                <a class="btn btn-amarillo submit" href="">LOGIN</a>

            </form>
            <form id="formRegister" action="" name="register" method="post">
                <h2>Join and <br/>create folio</h2>
                <label>                    
                    <input type="text" id="email" name="email" placeholder="Email address" class="" />
                </label>
                <label>
                    <input type="password" id="password" name="password"  placeholder="Password"   />
                </label>

                <a class="btn btn-amarillo submit liLight" href="/fase2/login/exclusive" data-form="formRegister">BECOME A MEMBER</a>
            </form>

        </div>
        <span class="closex">X</span>
    </div>
</div>
<script> 
    $('#formSignin .submit').click(function(e){
        e.preventDefault();
        $('#formSignin').submit();
        return false;
    })
    WTA.lightbox();
    WTA.signin();
</script>