<div class="wLight">
    <div id="signin" class="popup large">
        <div>
            <div>
                <img src="<?php echo STATIC_URL ?>/front-fase2/images/logo-degradado.png" />                
                <form id="formSignin" action="/member/login" name="signin" method="post">
                    <h1><img src="<?php echo STATIC_URL ?>/front-fase2/images/texts/welcome-back-sign-in.png" /></h1>
                    <label>                    
                        <input type="text" id="email" name="email" placeholder="Email address" class="" />
                    </label>
                    <label>
                        <input type="password" id="password" name="password"  placeholder="Password"   />
                    <label>
                    <!-- label><input type="checkbox" name="remember" value="1" /> Remember my session</labe l-->
                    <a class="forgot liLight" href="/fase2/forgotpass">FORGOT PASSWORD</a>
                    <a href="/fase2/why-join" class="forgot liLight" style="margin-top: 0px !important;">Become Member</a>
                    <br>
                    <a class="btn btn-negro submit" href="">Sign in</a>

                </form>
            </div>
        </div>
        <span class="closex">X</span>
    </div>
</div>
<script> 
    $('#formSignin .submit').click(function(e){
        e.preventDefault();
        $('#formSignin').submit();
        return false;
    })
    WTA.lightbox();
    WTA.signin();
</script>