
<div class="wLight" >
   <div  id="congratulations" class="popup large">
          <div class="" >
                <div class="closex">X</div>
                
                <img src="<?php echo STATIC_URL ?>/front-fase2/images/logo-degradado.png" />
                <h1 ><img src="<?php echo STATIC_URL ?>/front-fase2/images/texts/special-congratulations.png" /></h1> 
                <br/>
                <p>
                    Your Order Has been<br/>
                    processed for one of our<br/>
                    limited quantity selection. <br/>
                    Please check your<br/>
                    email for our Receipt.<br/><br/>
                    Have a fantastic day!
                </p>
                <a href="" class="btn btn-negro continue">Continue</a>
          </div>

       

    </div>

</div>
