
<div class="wLight" >
   <div  id="processed" class="popup">
          <div class="" >
                <div class="closex">X</div>
                <h1>
                        OOPS...
                </h1> 
                <br/>
                <p id="msgError">
                   There was something <br/>
                   wrong with your <br/>
                   credit card, please <br/>
                   try again.
                </p><br/><br/>
                <a href="" class="btn btn-negro continue">Continue</a>
          </div>

       

    </div>

</div>
<script>
    var error = WTA.getError();
    if(error){
        document.getElementById('msgError').innerHTML = error;
    }
</script>