
<div class="wLight" >
   <div  id="processed" class="popup">
          <div class="" >
                <div class="closex">X</div>
                <h1 ><img src="<?php echo STATIC_URL ?>/front-fase2/images/texts/thank-you.png" /></h1> 
                <br/>
                <p id="msgSuccess">
                    Your Order Has been<br/>
                    processed for one of our<br/>
                    limited quantity selection. <br/>
                    Please check your<br/>
                    email for our Receipt.<br/><br/>
                    Have a fantastic day!
                </p>
                <a href="" class="btn btn-negro continue">Continue</a>
          </div>

       

    </div>

</div>

<script>
    var error = WTA.getError();
    if(error){
        document.getElementById('msgSuccess').innerHTML = error;
    }
</script>